#!/usr/bin/env python
# coding: utf-8

# In[ ]:


pos_Words=['sedap','murah','padu','suka','terbaik','best','terliur','craving',
              'sedapnya','sedapnyaaaa','fresh','halal','berbaloi','mampu','nice','berpatutan',
               'baguslah','good','asyuk','istimewa','bersih','mantap','terbaek','teringgin',
               'shedappnyeeeeeeeee','trbaek','murahhh','segera','terbaikkkkkk','cair','cepat','indah','teringin',
              'teringinnnn','padu','terliur', 'memuaskan','enak','power','laku']
translated_pos_words=['melimpah ruah',
 'dipenuhi',
 'banyak',
 'banyak',
 'accessable',
 'diakses',
 'pujian',
 'terkenal',
 'sebulat',
 'anugerah',
 'penghargaan',
 'akomodatif',
 'akomodatif',
 'mencapai',
 'dicapai',
 'pencapaian',
 'pencapaian',
 'tepat',
 'tepat',
 'dicapai',
 'pencapaian',
 'pencapaian',
 'achievible',
 'kepintaran',
 'menyesuaikan diri',
 'penyesuaian',
 'mencukupi',
 'laras',
 'terpuji',
 'mengagumkan',
 'kekaguman',
 'mengagumi',
 'peminat',
 'mengagumi',
 'kagum',
 'comel',
 'memuja',
 'dipuja',
 'pemuja',
 'memuja',
 'adoringly',
 'adroit',
 'adroitly',
 'adulate',
 'sanjungan',
 'adulatory',
 'maju',
 'kelebihan',
 'berfaedah',
 'advantageously',
 'kelebihan',
 'adventuresome',
 'mencabar',
 'peguam bela',
 'menyokong',
 'penyokong',
 'affability',
 'mesra',
 'affably',
 'affectation',
 'kasih sayang',
 'penyayang',
 'pertalian',
 'mengesahkan',
 'ikrar',
 'afirmatif',
 'kemewahan',
 'mewah',
 'mampu',
 'berpatutan',
 'sesuai kemampuan',
 'afordable',
 'tangkas',
 'agilely',
 'ketangkasan',
 'bersetuju',
 'agreeableness',
 'secara menyenangkan',
 'semua-sekitar',
 'memikat',
 'alluringly',
 'altruistik',
 'berkorban',
 'memukau',
 'kagum',
 'kekaguman',
 'amazes',
 'menakjubkan',
 'menakjubkan',
 'bercita-cita tinggi',
 'bercita-cita',
 'memperbaiki',
 'yg setuju',
 'Ameniti',
 'keramahtamahan',
 'amiabily',
 'mesra',
 'amicability',
 'secara baik',
 'secara baik',
 'persahabatan',
 'mencukupi',
 'diterangkan',
 'menghiburkan',
 'lucu',
 'amusingly',
 'malaikat',
 'malaikat',
 'pendewaan',
 'rayuan',
 'merayu',
 'memuji',
 'ketara',
 'menghargai',
 'dihargai',
 'menghargai',
 'menghargai',
 'sejenak',
 'sesuai',
 'kelulusan',
 'terima',
 'bersemangat',
 'kalaulah',
 'semangat',
 'menyatakan dengan jelas',
 'aspirasi',
 'aspirasi',
 'bercita-cita',
 'jaminan',
 'jaminan',
 'memberi jaminan',
 'sesungguhnya',
 'menjamin',
 'mencengangkan',
 'hairan',
 'menakjubkan',
 'menghairankan',
 'terkejut',
 'mengherankan',
 'terkejut',
 'mengejutkan',
 'astoundingly',
 'dengan bijak',
 'perhatian',
 'tarikan',
 'menarik',
 'menarik',
 'Menyesuaikan',
 'boleh didengar',
 'letusan suara',
 'bertuah',
 'sahih',
 'berwibawa',
 'autonomi',
 'tersedia',
 'aver',
 'gemar',
 'avidly',
 'anugerah',
 'dianugerahkan',
 'anugerah',
 'kagum',
 'kagum',
 'awesome',
 'awesomely',
 'kehebatan',
 'kagum',
 'awsome',
 'tulang belakang',
 'seimbang',
 'tawaran',
 'cantik',
 'indah',
 'beautifullly',
 'indah',
 'mencantikkan',
 'kecantikan',
 'menggamit',
 'memberi isyarat',
 'memanggilkan',
 'memberi isyarat',
 'dipercayai',
 'believeable',
 'tercinta',
 'dermawan',
 'pemurah',
 'berfaedah',
 'benefisial',
 'benefisiari',
 'manfaat',
 'faedah',
 'kebajikan',
 'baik hati',
 'benifits',
 'terbaik',
 'terbaik yang diketahui',
 'paling berprestasi',
 'paling laris',
 'lebih baik',
 'lebih dikenali',
 'lebih baik daripada yang dijangkakan',
 'beutifully',
 'bercela',
 'memberkati',
 'berkat',
 'kebahagiaan',
 'bahagia',
 'bahagia',
 'bahagia',
 'blockbuster',
 'mekar',
 'berbunga',
 'meningkatkan',
 'montok',
 'bonus',
 'bonus',
 'boom',
 'berkembang pesat',
 'galakan',
 'terbatas',
 'yang banyak',
 'brainiest',
 'cerdas',
 'jenama baru',
 'berani',
 'keberanian',
 'bravo',
 'kejayaan',
 'kejayaan',
 'sesak nafas',
 'menakjubkan',
 'melegakan',
 'angin',
 'terang',
 'menerangi',
 'cerah',
 'terang',
 'kecemerlangan',
 'brilliances',
 'cemerlang',
 'cemerlang',
 'pantas',
 'persaudaraan',
 'bullish',
 'memberangsangkan',
 'memujuk',
 'bertenang',
 'menenangkan',
 'ketenangan',
 'keupayaan',
 'mampu',
 'cakap',
 'memikat',
 'menawan',
 'riang',
 'rebat tunai',
 'cashbacks',
 'menarik',
 'meraikan',
 'terkenal',
 'sambutan',
 'perayaan',
 'juara',
 'juara',
 'karisma',
 'berkarisma',
 'amal',
 'Pesona',
 'menawan',
 'Anehnya',
 'yang terpelihara kehormatannya',
 'lebih murah',
 'paling murah',
 'bersorak',
 'ceria',
 'riang',
 'menghargai',
 'dihargai',
 'kerub',
 'bergaya',
 'bahaduri',
 'adab',
 'kesopanan',
 'peradaban',
 'kejelasan',
 'klasik',
 'bergaya',
 'bersih',
 'bersih',
 'bersih',
 'kebersihan',
 'bersih',
 'jelas',
 'jelas',
 'dibersihkan',
 'lebih jelas',
 'jelas',
 'Clears',
 'pandai',
 'bijak',
 'Cohere',
 'kepaduan',
 'koheren',
 'padu',
 'berwarna-warni',
 'sebaik-baiknya',
 'keselesaan',
 'selesa',
 'dengan selesa',
 'selesa',
 'selesa',
 'memuji',
 'terpuji',
 'memberangsangkan',
 'komitmen',
 'lapang',
 'padat',
 'kemas',
 'belas kasihan',
 'penyayang',
 'serasi',
 'berdaya saing',
 'pelengkap',
 'pelengkap',
 'dilengkapi',
 'pelengkap',
 'yang mematuhi',
 'pujian',
 'percuma',
 'menyeluruh',
 'mendamaikan',
 'pendamai',
 'ringkas',
 'keyakinan',
 'yakin',
 'sehaluan',
 'mengucapkan tahniah kepada',
 'tahniah',
 'tahniah',
 'tahniah',
 'teliti',
 'bertimbang rasa',
 'konsisten',
 'konsisten',
 'membina',
 'dikalangan',
 'kepuasan',
 'kesinambungan',
 'contrasty',
 'sumbangan',
 'kemudahan',
 'sesuai',
 'tempatnya',
 'Convience',
 'convienient',
 'convient',
 'meyakinkan',
 'meyakinkan',
 'sejuk',
 'cool',
 'koperasi',
 'secara kerjasama',
 'asas',
 'betul',
 'betul',
 'kos efektif',
 'Jimat kos',
 'serangan balas',
 'serangan balas',
 'keberanian',
 'berani',
 'berani',
 'courageousness',
 'berbudi bahasa',
 'sopan',
 'perjanjian',
 'selesa',
 'kreatif',
 'kepercayaan',
 'boleh dipercayai',
 'segar',
 'crisper',
 'penawar',
 'menyembuhkan-semua',
 'enak',
 'comel',
 'kecomelan',
 'danke',
 'danken',
 'berani',
 'daringly',
 'darling',
 'kacak',
 'gagah',
 'subuh',
 'dazzle',
 'terpesona',
 'mempesonakan',
 'mati-murah',
 'mati-on',
 'kesopanan',
 'baik',
 'tegas',
 'ketegasan',
 'berdedikasi',
 'kekalahan',
 'dikalahkan',
 'mengalahkan',
 'kekalahan',
 'pertahanan',
 'rasa hormat',
 'deft',
 'deginified',
 'lazat',
 'makanan istimewa',
 'halus',
 'lazat',
 'kegembiraan',
 'gembira',
 'menarik',
 'menyenangkan',
 'delightfulness',
 'boleh dipercayai',
 'dependably',
 'sudah sepatutnya',
 'layak',
 'wajar',
 'berhasrat',
 'berhasrat',
 'takdir',
 'cerai',
 'taat',
 'tangkas',
 'dexterously',
 'tangkas',
 'bermaruah',
 'memartabatkan',
 'maruah',
 'usaha',
 'rajin',
 'bersungguh-sungguh',
 'diplomatik',
 'sangat murah',
 'perbezaan',
 'tersendiri',
 'dibezakan',
 'pelbagai',
 'ilahi',
 'ilahi',
 'menguasai',
 'dikuasai',
 'mendominasi',
 'sangat menyayangi',
 'dotingly',
 'pasti',
 'alam mimpi',
 'ternganga',
 'terus membingungkan',
 'dummy-bukti',
 'tahan lama',
 'dinamik',
 'bersemangat',
 'sabar',
 'kesungguhan',
 'bersungguh-sungguh',
 'bersungguh-sungguh',
 'kesungguhan',
 'meringankan',
 'susut',
 'makin berkurangan',
 'lebih mudah',
 'paling mudah',
 'kegampangan',
 'melonggarkan',
 'mudah',
 'mudah untuk digunakan',
 'mudah bergaul',
 'ebullience',
 'bersemangat baur-luap',
 'ebulliently',
 'ecenomical',
 'ekonomi',
 'ecstasies',
 'ecstasy',
 'gembira',
 'ecstatically',
 'memperbaiki akhlak',
 'berpendidikan',
 'berkesan',
 'berkesan',
 'keberkesanan',
 'berkesan',
 'berkesan',
 'berkesan',
 'cekap',
 'tanpa tenaga',
 'mudah',
 'lelehan',
 'effusive',
 'melampaui batas dlm Cocok',
 'effusiveness',
 'elan',
 'membesarkan hati',
 'gembira',
 'elatedly',
 'kegembiraan',
 'menggemparkan',
 'keanggunan',
 'elegan',
 'elegan',
 'meningkatkan',
 'elit',
 'kefasihan',
 'fasih',
 'fasih',
 'memberi semangat',
 'kemuliaan',
 'terkenal',
 'menjiwai',
 'empati',
 'memberi kuasa',
 'pemberdayaan',
 'memikat',
 'terpesona',
 'mempesonakan',
 'enchantingly',
 'menggalakkan',
 'galakan',
 'menggalakkan',
 'yang menjanjikan',
 'menimbulkan perasaan cinta',
 'monumental',
 'menyokong',
 'disahkan',
 'pengendorsan',
 'menyokong',
 'merestui',
 'bertenaga',
 'memberi tenaga',
 'tenaga yang cekap',
 'penjimatan tenaga',
 'menarik',
 'yg mengasyikkan',
 'meningkatkan',
 'dipertingkatkan',
 'peningkatan',
 'Meningkatkan',
 'menikmati',
 'menyeronokkan',
 'lebih gembira',
 'dinikmati',
 'menikmati',
 'keseronokan',
 'ianya',
 'menyedarkan',
 'pencerahan',
 'memeriahkan',
 'menggoncang',
 'cukup',
 'enrapt',
 'menawan hati',
 'terpesona',
 'memperkayakan',
 'pengayaan',
 'berdaya usaha',
 'melayan',
 'menghiburkan',
 'menghiburkan',
 'memukau',
 'memukau',
 'terpesona',
 'menarik minat',
 'semangat',
 'peminat',
 'bersemangat',
 'dengan penuh semangat',
 'menarik',
 'tertarik',
 'menarik',
 'enticingly',
 'terpesona',
 'yg',
 'mengamanahkan',
 'dicemburui',
 'enviably',
 'iri hati',
 'enviously',
 'enviousness',
 'iri hati',
 'saksama',
 'ergonomical',
 'sesat bebas',
 'terpelajar',
 'etika',
 'memuji-muji',
 'keghairahan',
 'euphoric',
 'euphorically',
 'menilai',
 'sama rata',
 'penuh peristiwa',
 'yang kekal',
 'anggun',
 'bertasbih',
 'tasbih',
 'mulia',
 'exaltedly',
 'meninggikan',
 'exaltingly',
 'examplar',
 'teladan',
 'excallent',
 'melebihi',
 'melebihi',
 'melebihi',
 'sangat',
 'melebihi',
 'excel',
 'exceled',
 'excelent',
 'excellant',
 'cemerlang',
 'kecemerlangan',
 'keluhuran',
 'sangat baik',
 'cemerlang',
 'cemerlang',
 'yang luar biasa',
 'sangat',
 'merangsang',
 'teruja',
 'teruja',
 'excitedness',
 'keseronokan',
 'merangsang',
 'mengujakan',
 'excitingly',
 'exellent',
 'teladan',
 'teladan',
 'meriangkan',
 'menyeronokkan',
 'exhilaratingly',
 'kegembiraan',
 'melepaskan',
 'luas',
 'cepat',
 'expertly',
 'indah',
 'indah',
 'memuji',
 'memuja',
 'luar biasa',
 'luar biasa',
 'penuh semangat',
 'bersemangat',
 'dengan penuh bersemangat',
 'bermegah-megah',
 'bermegah-megah',
 'kegirangan',
 'exultingly',
 'mata-tangkapan',
 'menarik perhatian',
 'eyecatch',
 'eyecatching',
 'hebat',
 'fabulously',
 'memudahkan',
 'berpatutan',
 'agak',
 'keadilan',
 'iman',
 'setia',
 'setia',
 'kesetiaan',
 'kemasyhuran',
 'terkenal',
 'terkenal',
 'terkenal',
 'pelamun',
 'fancinating',
 'mewah',
 'sebarang gangguan',
 'peminat',
 'hebat',
 'fantastically',
 'mempesona',
 'menarik',
 'fascinatingly',
 'daya tarikan',
 'bergaya',
 'bergaya',
 'cepat',
 'pantas berkembang',
 'pantas',
 'lebih cepat',
 'paling laju',
 'paling pesat berkembang',
 'bebas dari kesalahan',
 'fav',
 'fave',
 'memihak',
 'baik',
 'disukai',
 'kegemaran',
 'menggemari',
 'memihak',
 'berani',
 'tanpa rasa takut',
 'dilaksanakan',
 'layak di',
 'feat',
 'ciri-kaya',
 'fecilitous',
 'Feisty',
 'membahagiakan',
 'sangat tepat',
 'kebahagiaan',
 'subur',
 'sungguh-sungguh',
 'bersungguh-sungguh',
 'bersemangat',
 'fervidly',
 'semangat',
 'perayaan',
 'kesetiaan',
 'berapi-api',
 'denda',
 'denda yang berpandangan',
 'halus',
 'lebih halus',
 'terbaik',
 'lebih kukuh',
 'kelas pertama',
 'pertama dalam kelasnya',
 'Kelas pertama',
 'flashy',
 'mendatar',
 'memuji-muji',
 'flatteringly',
 'sempurna',
 'dengan sempurna',
 'fleksibiliti',
 'fleksibel',
 'berkembang',
 'berkembang',
 'fasih',
 'debar',
 'gemar',
 'mesra dengan panggilan',
 'kesukaan',
 'foolproof',
 'sekali',
 'pandangan jauh',
 'menggerunkan',
 'ketabahan',
 'kebetulan',
 'kebetulan',
 'bernasib baik',
 'nasib baik',
 'nasib',
 'wangi',
 'percuma',
 'dibebaskan',
 'kebebasan',
 'kebebasan',
 'segar',
 'segar',
 'segar',
 'keramahan',
 'mesra',
 'bermain-main',
 'berjimat',
 'berhasil',
 'ftw',
 'memenuhi',
 'menyeronokkan',
 'futurestic',
 'futuristik',
 'keriangan',
 'dengan gembira',
 'keuntungan',
 'mendapat',
 'yang menguntungkan',
 'secara bermanfaat',
 'mendapat',
 'keuntungan',
 'gagah',
 'berani',
 'computer',
 'geekier',
 'geeky',
 'permata',
 'permata',
 'kemurahan hati',
 'murah hati',
 'murah hati',
 'genial',
 'genius',
 'lembut',
 'gentlest',
 'tulen',
 'berbakat',
 'gembira',
 'menggembirakan',
 'dengan senang hati',
 'sukacita',
 'glamor',
 'geli',
 'riang gembira',
 'penuh teruja',
 'berkilau',
 'kelip redup',
 'berkaca-kaca',
 'berkilauan',
 'glitter',
 'glitz',
 'memuliakan',
 'gemilang',
 'gilang-gemilang',
 'kemuliaan',
 'bersinar',
 'bercahaya',
 'glowingly',
 'tuhan-diberikan',
 'tuhan-send',
 'tahyul',
 'rahmat',
 'emas',
 'emas',
 'baik',
 'yang baik',
 'kebaikan',
 'nama baik',
 'goood',
 'gooood',
 'cantik',
 'gorgeously',
 'rahmat',
 'anggun',
 'anggun',
 'pengasih',
 'anggun',
 'keanggunan',
 'grand',
 'kemegahan',
 'berterima kasih',
 'terima kasih',
 'kepuasan',
 'berpuas hati',
 'gratifies',
 'gratify',
 'memuaskan',
 'gratifyingly',
 'terima kasih',
 'hebat',
 'pilihan',
 'kebesaran',
 'senyuman',
 'pecah tanah',
 'Jaminan',
 'panduan',
 'bersalah',
 'kecerdasan',
 'terpancut',
 'gusto',
 'gutsy',
 'hujan batu',
 'tenang dan damai',
 'hale',
 'ciri',
 'mercu',
 'keramat',
 'handier',
 'ringan tangan',
 'tangan-down',
 'kacak',
 'lumayan',
 'berguna',
 'lebih bahagia',
 'bahagia',
 'kebahagiaan',
 'gembira',
 'rajin',
 'hardier',
 'tahan lasak',
 'tidak berbahaya',
 'harmoni',
 'harmoni',
 'menyelaraskan',
 'keharmonian',
 'kemajuan',
 'sembuh',
 'sihat',
 'sihat',
 'membesarkan hati',
 'menggembirakan',
 'tulus',
 'sepenuh hati',
 'mengharukan',
 'Syurga',
 'syurga',
 'membantu',
 'berguna',
 'membantu',
 'wira',
 'berani',
 'heroically',
 'heroin',
 'heroize',
 'heros',
 'kualiti tinggi',
 'bersemangat tinggi',
 'kelakar',
 'suci',
 'penghormatan',
 'jujur',
 'kejujuran',
 'penghormatan',
 'mulia',
 'dihormati',
 'menghormati',
 'hooray',
 'berharap',
 'peramah',
 'panas',
 'kek panas',
 'kek panas',
 'panas',
 'peluk',
 'berperikemanusiaan',
 'merendah diri',
 'rendah hati',
 'humor',
 'lucu',
 'humorously',
 'humor',
 'kelakar',
 'ideal',
 'mengidealkan',
 'lokasi strategik',
 'Idol',
 'memuja',
 'pujaan',
 'indah',
 'menerangi',
 'illuminati',
 'Illuminating',
 'menerangi',
 'terkenal',
 'ilu',
 'imaculate',
 'imaginatif',
 'rapi',
 'rapi',
 'besar',
 'tidak berat sebelah',
 'kesaksamaan',
 'saksama',
 'berapi-api',
 'cemerlang',
 'cela',
 'penting',
 'menarik perhatian',
 'kagum',
 'mengesankan',
 'mengesankan',
 'hebatnya',
 'impressiveness',
 'meningkatkan',
 'bertambah baik',
 'peningkatan',
 'penambahbaikan',
 'meningkatkan',
 'meningkatkan',
 'yang luar biasa',
 'sangat',
 'terhutang budi',
 'individu',
 'kepuasan',
 'memenuhi segala keinginan',
 'rajin',
 'tak ternilai',
 'inestimably',
 'murah',
 'kemaksuman',
 'maksum',
 'infallibly',
 'berpengaruh',
 'bijak',
 'ingeniously',
 'kepintaran',
 'tulus',
 'ingenuously',
 'berbahaya',
 'inovasi',
 'inovatif',
 'inpressed',
 'berwawasan',
 'insightfully',
 'inspirasi',
 'inspirasi',
 'memberi inspirasi',
 'inspirasi',
 'serta-merta',
 'pengajaran',
 'instrumental',
 'integral',
 'bersepadu',
 'kecerdasan',
 'bijak',
 'difahami',
 'menarik',
 'kepentingan',
 'keintiman',
 'intim',
 'rumit',
 'tipu muslihat',
 'menarik',
 'intriguingly',
 'intuitif',
 'yang tidak ternilai',
 'invaluablely',
 'berdaya cipta',
 'para',
 'menyegarkan',
 'kekebalan',
 'kebal',
 'dicabul',
 'dilanggar',
 'kebal',
 'boleh ditukar ganti',
 'tak bercacat',
 'sangat menarik',
 'mendesak',
 'isu-percuma',
 'rahang-droping',
 'mengagumkan',
 'sedikit mabuk',
 'riang',
 'baik hati dan gembira',
 'kegembiraan',
 'riang',
 'gembira',
 'meriah',
 'meriah',
 'gembira',
 'sorak',
 'bergembira sekali',
 'kegembiraan',
 'jubiliant',
 'bijak',
 'adil',
 'berminat',
 'dengan penuh minat',
 'kesungguhan',
 'mesra kanak-kanak',
 'sifat baik hati',
 'sila',
 'kebaikan',
 'berpengetahuan',
 'pujian',
 'berkapasiti besar',
 'memuji',
 'patut dipuji',
 'laudably',
 'mewah',
 'mewah',
 'mematuhi undang-undang',
 'sah',
 'menurut undang-undang',
 'membawa',
 'mengetuai',
 'petunjuk',
 'tanpa lemak',
 'membawa',
 'legenda',
 'leverage',
 'kesembronoan',
 'membebaskan',
 'pembebasan',
 'kebebasan',
 'lifesaver',
 'cahaya hati',
 'lebih ringan',
 'disenangi',
 'seperti',
 'suka',
 'orang seperti',
 'keinginan',
 'lionhearted',
 'meriah',
 'logik',
 'tahan lama',
 'dicintai',
 'lovably',
 'suka',
 'suka',
 'loveliness',
 'indah',
 'kekasih',
 'suka',
 'penyayang',
 'kos rendah',
 'harga rendah',
 'rendah dari',
 'risiko rendah',
 'yang lebih murah',
 'setia',
 'kesetiaan',
 'cerah',
 'lucidly',
 'nasib',
 'bernasib baik',
 'paling bertuah',
 'luckiness',
 'bertuah',
 'lumayan',
 'bercahaya',
 'subur',
 'kilau',
 'berkilau',
 'subur',
 'menikmatkan',
 'mewah',
 'mewah',
 'mewah',
 'lirik',
 'sihir',
 'ajaib',
 'murah hati',
 'magnanimously',
 'keindahan',
 'indah',
 'indah-indah',
 'megah',
 'keagungan',
 'diurus',
 'mudah dikendalikan',
 'kehebatan',
 'kagum',
 'kagum',
 'menakjubkan',
 'menakjubkan',
 'menakjubkan',
 'marvelousness',
 'keajaiban',
 'master',
 'menguasai',
 'masterfully',
 'karya',
 'karya-karya',
 'tuan',
 'penguasaan',
 'yang tiada taranya',
 'matang',
 'matang',
 'kematangan',
 'bermakna',
 'kenangan',
 'pengasih',
 'belas kasihan',
 'belas kasihan',
 'merit',
 'berjasa',
 'riang',
 'keriangan',
 'merriness',
 'selamat hari raya',
 'memukau',
 'terpesona',
 'mesmerizes',
 'memukau',
 'mempesonakan',
 'teliti',
 'teliti',
 'dgn kuat',
 'besar',
 'fikiran-bertiup',
 'keajaiban',
 'keajaiban',
 'ajaib',
 'ajaib',
 'miraculousness',
 'moden',
 'sederhana',
 'kesopanan',
 'bersejarah',
 'monumental',
 'monumentally',
 'moral',
 'bermotivasi',
 'pelbagai fungsi',
 'dilayari',
 'kemas',
 'neatest',
 'kemas',
 'nice',
 'baik',
 'lebih bagus',
 'paling baik',
 'bagus',
 'lincah',
 'mulia',
 'dgn baik hati',
 'tak bersuara',
 'bukan keganasan',
 'bukan ganas',
 'terutamanya',
 'perlu diberi perhatian',
 'menyuburkan',
 'berkhasiat',
 'khasiat',
 'sesuatu yang baru',
 'asuhan',
 'oasis',
 'obsesi',
 'obsessions',
 'diperolehi',
 'secara terbuka',
 'keterbukaan',
 'optimum',
 'keyakinan',
 'optimis',
 'mewah',
 'teratur',
 'keaslian',
 'mengalahkan',
 'kalah',
 'mengatasi',
 'mengatasi',
 'mengatasi',
 'melebihi performa',
 'lebih bernas dr',
 'outshone',
 'mengakali',
 'tertunggak',
 'dengan cemerlang',
 'mendahului',
 'mengakali',
 'tepukan',
 'gembira',
 'mengatasi',
 'diambil alih',
 'didatangi',
 'memotong',
 'menimpa',
 'pembukaan',
 'sakit-percuma',
 'menyakitkan',
 'tanpa rasa sakit',
 'mewah',
 'memanjakan',
 'dimanjakan',
 'pamperedly',
 'pamperedness',
 'pampers',
 'panorama',
 'syurga',
 'paling utama',
 'pengampunan',
 'semangat',
 'ghairah',
 'ghairah',
 'kesabaran',
 'pesakit',
 'sabar',
 'patriot',
 'patriotik',
 'keamanan',
 'damai',
 'aman',
 'aman',
 'pasukan pengaman',
 'pic',
 'peerless',
 'pep',
 'pepped',
 'pepping',
 'penuh semangat',
 'peps',
 'sempurna',
 'kesempurnaan',
 'dengan sempurna',
 'dibenarkan',
 'ketabahan',
 'tabah',
 'tokoh',
 'peribadi',
 'luar biasa',
 'phenomenally',
 'indah',
 'ketakwaan',
 'puncak',
 'suka bermain',
 'main-main',
 'dapat',
 'gembira',
 'gembira',
 'dikehendakiNya',
 'menyenangkan',
 'pleasingly',
 'menyeronokkan',
 'dengan gembira',
 'keseronokan',
 'banyak',
 'plus',
 'plush',
 'plusses',
 'syair',
 'keindahan puisi',
 'memilukan',
 'sikap tenang',
 'bersedia',
 'digilap',
 'sopan',
 'kesopanan',
 'popular',
 'mudah alih',
 'posh',
 'positif',
 'positif',
 'positif',
 'kuat',
 'kuat',
 'pujian',
 'terpuji',
 'memuji',
 'terunggul',
 'berharga',
 'tepat',
 'tepat',
 'cemerlang',
 'lebih suka',
 'lebih',
 'sebaik-baiknya',
 'memilih',
 'preferes',
 'lebih suka',
 'lebih suka',
 'premier',
 'prestij',
 'berprestij',
 'dgn bagus',
 'cantik',
 'ternilai',
 'kebanggaan',
 'berprinsip',
 'keistimewaan',
 'istimewa',
 'hadiah',
 'proaktif',
 'bebas masalah',
 'penyelesai masalah',
 'luar biasa',
 'prodigiously',
 'ajaib',
 'produktif',
 'produktif',
 'cekap',
 'cekap',
 'mendalam',
 'mendalam',
 'sedalam-dalamnya',
 'kelimpahan',
 'kemajuan',
 'progresif',
 'prolifik',
 'terkenal',
 'menonjol',
 'janji',
 'berjanji',
 'janji',
 'menjanjikan',
 'promoter',
 'segera',
 'segera',
 'betul',
 'betul',
 'kemakmuran',
 'propitiously',
 'pro',
 'berjaya',
 'kemakmuran',
 'Makmur',
 'prospros',
 'melindungi',
 'perlindungan',
 'perlindungan',
 'bangga',
 'terbukti',
 'membuktikan',
 'rezeki',
 'membuktikan',
 'kehebatan',
 'berhemah',
 'berhemat',
 'berhemah',
 'menepati masa',
 'tulen',
 'menyucikan',
 'azam',
 'aneh',
 'berkelayakan',
 'layak',
 'lebih cepat',
 'senyap',
 'senyap',
 'seri',
 'berseri',
 'pesat',
 'hubungan',
 'asyik',
 'pengangkatan',
 'raptureous',
 'raptureously',
 'yg membayangkan kegembiraan hati',
 'rapturously',
 'rasional',
 'tajam',
 'dapat dihubungi',
 'boleh dibaca',
 'mudah',
 'bersedia',
 'mengesahkan',
 'penegasan',
 'realistik',
 'realisasi',
 'munasabah',
 'munasabah',
 'alasan',
 'jaminan',
 'meyakinkan',
 'menerima',
 'menuntut semula',
 'recomend',
 'mengesyorkan',
 'cadangan',
 'cadangan',
 'disyorkan',
 'mendamaikan',
 'perdamaian',
 'rekod penetapan',
 'pulih',
 'pemulihan',
 'pembetulan',
 'memperbetulkan',
 'membetulkan',
 'menebus',
 'menebus',
 'penebusan',
 'mendapatkan hasil',
 'halus',
 'perbaikan',
 'pembaharuan',
 'diperbaharui',
 'pembaharuan',
 'pembaharuan',
 'refresh',
 'segar',
 'menyegarkan',
 'bayaran balik',
 'balik',
 'regal',
 'seperti raja',
 'Sehubungan',
 'bergembira',
 'bergembira',
 'ria gembira',
 'memberi nafas baru',
 'nafas baru',
 'meremajakan',
 'menyeronokkan',
 'berlembut',
 'dipercayai',
 'pasti',
 'relief',
 'lauk',
 'luar biasa',
 'amat',
 'ubat',
 'pengampunan',
 'imbuhan',
 'kebangkitan',
 'diperbaharui',
 'terkenal',
 'terkenal',
 'diganti',
 'bereputasi',
 'reputasi',
 'berdaya tahan',
 'tegas',
 'bergema',
 'membanggakan',
 'pintar',
 'kepintaran',
 'berkenaan',
 'dihormati',
 'menghormati',
 'hormat',
 'diberi tempoh',
 'gemilang',
 'secara bertanggungjawab',
 'responsif',
 'tenang',
 'dipulihkan',
 'menyusun semula',
 'disusun semula',
 'penyusunan semula',
 'ditarik balik',
 'bersenang-senang',
 'wahyu',
 'menghormati',
 'hormat',
 'penuh hormat',
 'dengan penuh hormat',
 'memulihkan semula',
 'kebangkitan semula',
 'memulihkan',
 'menghidupkan',
 'revolusi',
 'merevolusikan',
 'merevolusikan',
 'merevolusi',
 'ganjaran',
 'ganjaran',
 'rewardingly',
 'kaya',
 'lebih kaya',
 'kaya',
 'kekayaan',
 'betul',
 'righten',
 'soleh',
 'adil',
 'kebenaran',
 'sah',
 'berhak',
 'betul',
 'kebetulan',
 'bebas risiko',
 'teguh',
 'rock bintang',
 'rock-bintang',
 'rockstar',
 'Rockstars',
 'romantis',
 'romantis',
 'meromantisir',
 'roomier',
 'lapang',
 'rosy',
 'selamat',
 'selamat',
 'kebijaksanaan',
 'sagely',
 'saint',
 'hidup tanpa dosa',
 'suci',
 'menyihatkan',
 'salute',
 'waras',
 'dengan memuaskan',
 'memuaskan',
 'berpuas hati',
 'memuaskan',
 'Puaskan',
 'memuaskan',
 'satisified',
 'penjimat',
 'simpanan',
 'Penyelamat',
 'celik',
 'indah',
 'lancar',
 'berpengalaman',
 'selamat',
 'selamat',
 'terpilih',
 'penentuan nasib sendiri',
 'hormat diri',
 'kepuasan diri',
 'sara diri',
 'berdikari',
 'sensasi',
 'sensasi',
 'sensasi',
 'sensasi',
 'waras',
 'bijaksana',
 'sensitif',
 'tenang',
 'ketenangan',
 'sexy',
 'tajam',
 'lebih tajam',
 'paling ketara',
 'berkilauan',
 'shimmeringly',
 'bersinar',
 'berkilat',
 'ketara',
 'senyap',
 'mudah',
 'paling mudah',
 'dipermudahkan',
 'Permudah',
 'memudahkan',
 'memudahkan',
 'ikhlas',
 'ikhlas',
 'ikhlas',
 'kemahiran',
 'mahir',
 'mahir',
 'mahir',
 'Slammin',
 'anggun',
 'licin',
 'pintar',
 'lebih bijak',
 'bijak',
 'bijak',
 'senyuman',
 'senyuman',
 'tersenyum',
 'tersenyum',
 'kejangkitan',
 'licin',
 'licin',
 'melicin',
 'smoothest',
 'lancar',
 'solek',
 'manis',
 'pandai bergaul',
 'lembut',
 'lebih lembut',
 'ketenangan',
 'kuatir',
 'solicitously',
 'pepejal',
 'perpaduan',
 'melegakan',
 'dgn tenang',
 'canggih',
 'penuh perasaan',
 'nyenyak',
 'kekukuhan',
 'luas',
 'berkilau',
 'berkilau',
 'menakjubkan',
 'spektakuler',
 'cepat',
 'cepat',
 'mempesonakan',
 'mempesonakan',
 'spellbindingly',
 'terpesona',
 'bersemangat',
 'rohani',
 'indah',
 'dgn baik',
 'keindahan',
 'spontan',
 'sporty',
 'bersih',
 'riang gembira',
 'kestabilan',
 'menstabilkan',
 'stabil',
 'tahan karat',
 'menonjol',
 'state-of-the-art',
 'mewah',
 'patung',
 'kuat',
 'berpegang kuat dengan ajaran',
 'staunchness',
 'teguh',
 'sabar',
 'sabar',
 'steadiest',
 'keunggulan',
 'mantap',
 'cemerlang',
 'stellarly',
 'merangsang',
 'merangsang',
 'merangsang',
 'merangsang',
 'stirringly',
 'meluruskan',
 'mudah',
 'diselaraskan',
 'menarik',
 'sungguh menarik',
 'berusaha',
 'kuat',
 'kuat',
 'kuat',
 'terkejut',
 'menakjubkan',
 'disetiap',
 'bukan kepalang',
 'stupendously',
 'sturdier',
 'kukuh',
 'bergaya',
 'bergaya',
 'digayakan',
 'suave',
 'suavely',
 'luhur',
 'subsidi',
 'subsidi',
 'subsidi',
 'subsidi',
 'substantif',
 'berjaya',
 'berjaya',
 'berjaya',
 'berjaya',
 'succes',
 'kejayaan',
 'kejayaan',
 'berjaya',
 'berjaya',
 'memadai',
 'cukup',
 'mencukupi',
 'mencukupi',
 'cukup',
 'sesuai',
 'mewah',
 'kemewahan',
 'kemewahan',
 'super',
 'hebat',
 'dengan hebatnya',
 'unggul',
 'keunggulan',
 'lembut',
 'sokongan',
 'disokong',
 'penyokong',
 'sokongan',
 'sokongan',
 'sokongan',
 'ketuanan',
 'tertinggi',
 'supremely',
 'supurb',
 'supurbly',
 'mengatasi',
 'mengatasi',
 'nyata',
 'survival',
 'yang masih hidup',
 'kemampanan',
 'mampan',
 'menyombong',
 'swankier',
 'swankiest',
 'angkuh',
 'menyapu',
 'gula',
 'memaniskan',
 'kekasih',
 'manis',
 'kemanisan',
 'swift',
 'kepantasan',
 'bakat',
 'berbakat',
 'bakat',
 'menggoda',
 'menggiurkan',
 'tantalizingly',
 'menggoda',
 'menggoda',
 'temptingly',
 'gigih',
 'degil',
 'ketabahan',
 'tender',
 'lembut',
 'hebat',
 'terrifically',
 'terima kasih',
 'bersyukur',
 'nipis',
 'difikirkan',
 'teliti',
 'bertimbang rasa',
 'berjimat cermat',
 'berjimat-cermat',
 'keseronokan',
 'teruja',
 'mendebarkan',
 'thrillingly',
 'keseronokan',
 'berkembang maju',
 'berkembang maju',
 'thumb-up',
 'pujian',
 'menggelitik',
 'kemas',
 'masa dihormati',
 'tepat pada masanya',
 'tingle',
 'menggelitik',
 'titillating',
 'titillatingly',
 'kebersamaan',
 'boleh tahan',
 'bebas tol',
 'bahagian',
 'kedudukan tertinggi',
 'kualiti terbaik',
 'kedudukan tertinggi',
 'puncak',
 'sukar',
 'sukar',
 'paling sukar',
 'daya tarikan',
 'tenang',
 'ketenangan',
 'telus',
 'harta',
 'dengan hebat',
 'bergaya',
 'kejayaan',
 'kemenangan',
 'berjaya',
 'megah',
 'trivially',
 'trofi',
 'bebas masalah',
 'muslihat',
 'sangkakala',
 'amanah',
 'dipercayai',
 'percaya',
 'trustingly',
 'amanah',
 'boleh dipercayai',
 'kepercayaan',
 'benar',
 'dengan benar',
 'kebenaran',
 'twinkly',
 'ultra-tajam',
 'yang jelas',
 'segan silu',
 'tidak terjejas',
 'dapat disangkal',
 'hebat',
 'tidak berat sebelah',
 'tak terbatas',
 'tidak rumit',
 'tanpa syarat',
 'tidak rosak',
 'gentar',
 'difahami',
 'tidak disangkalkan',
 'undisputably',
 'dipertikaikan',
 'tiada halangan untuk menggunakannya',
 'berbelah',
 'tanpa ragu-ragu',
 'tidak gentar',
 'tidak terbatas',
 'dapat',
 'perpaduan',
 'yang tidak terhad',
 'tidak dapat ditandingi',
 'hebat',
 'tidak boleh dipersoalkan',
 'memang tidak disangkalkan lagi',
 'tidak benar',
 'tanpa had',
 'yang tiada tandingan',
 'mementingkan diri sendiri',
 'tidak berbelah bahagi',
 'yakin',
 'upgradable',
 'upgradeable',
 'dinaik taraf',
 'mengekalkan',
 'menegakkan',
 'uplift',
 'menaikkan semangat',
 'upliftingly',
 'meningkatkan taraf',
 'kelas atas',
 'boleh digunakan',
 'boleh digunakan',
 'berguna',
 'mesra pengguna',
 'pengguna diganti',
 'berani',
 'yang gagah perkasa,',
 'keberanian',
 'berharga',
 'pelbagai',
 'menghormati',
 'disahkan',
 'dipenuhi',
 'serba boleh',
 'serba boleh',
 'lawatan',
 'vibrantly',
 'menang',
 'kemenangan',
 'mana boleh dilihat',
 'kewaspadaan',
 'berjaga-jaga',
 'menurut',
 'mulia',
 'virtuously',
 'berwawasan',
 'riang',
 'terang',
 'menjamin',
 'Kurniakanlah',
 'panas',
 'lebih panas',
 'warmhearted',
 'mesra',
 'kehangatan',
 'kaya',
 'selamat datang',
 'baik',
 'yang backlit',
 'yang seimbang',
 'yg berkelakuan baik',
 'kesejahteraan',
 'sopan santun',
 'baik-baik',
 'berpelajaran tinggi',
 'mantap',
 'bermaklumat',
 'berniat baik',
 'yang diketahui',
 'dibuat dengan baik',
 'diurus dengan baik',
 'bersopan santun',
 'dalam kedudukan yang baik',
 'diterima dengan baik',
 'dianggap baik',
 'serba boleh',
 'diuruskan dengan baik',
 'mengambil berat',
 'kesejahteraan',
 'wah',
 'dengan sepenuh hati',
 'sihat',
 'whooa',
 'whoooa',
 'wieldy',
 'sanggup',
 'rela',
 'kesanggupan',
 'kemenangan',
 'durian runtuh',
 'boleh menang',
 'pemenang',
 'pemenang',
 'memenangi',
 'kemenangan',
 'kebijaksanaan',
 'bijak',
 'dengan bijak',
 'lucu',
 'menang',
 'tertanya-tanya',
 'indah',
 'hebat',
 'wonderous',
 'wonderously',
 'keajaiban',
 'menakjubkan',
 'woo',
 'kerja',
 'boleh digunakan',
 'bekerja',
 'kerja-kerja',
 'terkenal di dunia',
 'bernilai',
 'bernilai-semasa',
 'kepercayaan',
 'berbaloi',
 'layak',
 'wow',
 'wowed',
 'wowing',
 'wows',
 'yay']
                          
neg_Words=['pedas', 'kering', 'tak_berkualiti'
 'kotor',
 'rabak',              
 'busuk',
 'tawar',
 'xsedap',
 'xfresh',
 'tak_fresh',
 'xberbaloi',
 'teruk',
 'mahal',
 'ngecewakn',
 'terok',
 'lemak',
 'keras',
 'kecewa',              
 'menyesal',
 'pelik',
 'mengarut',
 'terpedaya',
 'susah',
 'gastrik',
 'berminyak',
 'kecik',
 'tidak_selesa',
 'muak',
 'tak_mampu',
 'mengamuk',
 'tidak_mampu',
 'tak_berkualiti',
 'mengecewakan',
 'masin','tipu','tknk','tak_sedap','bukan_sedap','tidak_sedap','tidak_selesa',
 'tidak_baik','tidak_mampu','tak_mampu','tak_baik','tak_selesa','kurang_memuaskan',
 'kurang_sedap', 'kurang_baik']

translated_neg_words = ['tidak normal',
 'menghapuskan',
 'keji',
 'abominably',
 'abominate',
 'kekejian',
 'membatalkan',
 'digugurkan',
 'aborts',
 'abrade',
 'kasar',
 'mendadak',
 'tiba-tiba',
 'melarikan diri',
 'ketiadaan',
 'pelupa',
 'tidak hadir',
 'tidak masuk akal',
 'kemustahilan',
 'bukan kepalang',
 'absurdness',
 'penyalahgunaan',
 'disalahgunakan',
 'penyalahgunaan',
 'kesat',
 'kepalang',
 'abysmally',
 'jurang',
 'kemalangan',
 'menegur',
 'terkutuk',
 'tuduhan',
 'tuduhan',
 'menuduh',
 'menuduh',
 'menuduh',
 'accusingly',
 'acerbate',
 'acerbic',
 'acerbically',
 'sakit',
 'sakit',
 'sakit',
 'Achey',
 'sakit',
 'menusuk hidung',
 'acridly',
 'acridness',
 'agak hebat',
 'acrimoniously',
 'acrimony',
 'berkeras',
 'bulat-bulat',
 'penagih',
 'ketagih',
 'addicting',
 'penagih',
 'beri amaran',
 'admonisher',
 'admonishingly',
 'teguran',
 'pelajaran',
 'memalsukan',
 'dicemari',
 'pencemaran',
 'adulterier',
 'pertentangan',
 'musuh',
 'buruk',
 'kesengsaraan',
 'menimpa',
 'penderitaan',
 'pedih',
 'penghinaan',
 'takut',
 'memburukkan',
 'memburukkan',
 'gangguan',
 'pencerobohan',
 'agresif',
 'agresif',
 'penyerang',
 'akan berdukacita',
 'terkilan',
 'aggrivation',
 'terkejut',
 'penderitaan',
 'menderita',
 'menyeksakan',
 'agonizingly',
 'kesakitan',
 'terkandas',
 'ail',
 'sakit',
 'penyakit',
 'tiada tujuan',
 'penggera',
 'cemas',
 'membimbangkan',
 'makin',
 'merenggangkan',
 'terasing',
 'pengasingan',
 'dakwaan',
 'dakwaan',
 'mendakwa',
 'alahan',
 'alahan',
 'alahan',
 'menyendiri',
 'perbalahan',
 'kekaburan',
 'samar-samar',
 'pertentangan',
 'ambivalen',
 'serangan hendap',
 'kena',
 'memotong',
 'anarkisme',
 'anarkis',
 'anarki',
 'anarki',
 'anemia',
 'kemarahan',
 'marah',
 'angriness',
 'marah',
 'kesedihan',
 'permusuhan',
 'menghapuskan',
 'penghapusan',
 'menyakitkan hati',
 'kegusaran',
 'gangguan',
 'marah',
 'menjengkelkan',
 'annoyingly',
 'menyakitkan hati',
 'ganjil',
 'anomali',
 'permusuhan',
 'antagonis',
 'bermusuhan',
 'kemarahan',
 'anti-',
 'anti-american',
 'anti-Israel',
 'anti-penjajahan',
 'anti-proliferasi',
 'anti-Semit',
 'anti-sosial',
 'anti-us',
 'anti-putih',
 'antipati',
 'kuno',
 'bertentangan',
 'kebimbangan',
 'kebimbangan',
 'cemas',
 'cemas',
 'kerisauan',
 'bersikap tidak peduli',
 'apathetically',
 'sikap acuh tak acuh',
 'wahyu',
 'dahsyat',
 'pembela',
 'apologis',
 'menggemparkan',
 'menggemparkan',
 'terkejut',
 'mengerikan',
 'menggemparkan',
 'kebimbangan',
 'bimbang',
 'bimbang',
 'apprehensively',
 'sewenang-wenangnya',
 'sukar difahami',
 'kuno',
 'sukar',
 'arduously',
 'bertengkar',
 'keangkuhan',
 'sombong',
 'sombong',
 'malu',
 'bodoh',
 'asininely',
 'asinininity',
 'dgn curiga',
 'asperse',
 'fitnah',
 'aspersions',
 'mencela',
 'Pembunuh',
 'membunuh',
 'serangan',
 'mengamang',
 'sesat',
 'belah',
 'kejam',
 'kekejaman',
 'kekejaman',
 'atrofi',
 'serang',
 'serangan',
 'berani',
 'audaciously',
 'keberanian',
 'keberanian',
 'audiciously',
 'sederhana',
 'autoritarian',
 'autocrat',
 'autokratik',
 'runtuhan',
 'ketamakan',
 'tamak',
 'avariciously',
 'membalas dendam',
 'suka',
 'kebencian',
 'aweful',
 'mengerikan',
 'mengerikan',
 'awfulness',
 'janggal',
 'kejanggalan',
 'kapak',
 'celoteh',
 'back-log',
 'back-kayu',
 'back-hutan',
 'sakit belakang',
 'sakit belakang',
 'backaching',
 'mengumpat',
 'mengumpat',
 'ke belakang',
 'kemunduran',
 'backwood',
 'terpencil',
 'buruk',
 'teruk',
 'sesekat',
 'bingung',
 'kebingungan',
 'mengherankan',
 'umpan',
 'balk',
 'cetek',
 'banalize',
 'bane',
 'membuang',
 'buang negeri',
 'bankrap',
 'gasar',
 'kejam',
 'barbarically',
 'kekejaman',
 'kejam',
 'barbarously',
 'mandul',
 'tidak berasas',
 'bash',
 'dibelasah',
 'segan',
 'menghentam',
 'anak haram',
 'anak haram',
 'didera',
 'alat pemukul',
 'amuk',
 'bearish',
 'jijik',
 'gempar',
 'orang gila',
 'mengotorkan',
 'beg',
 'pengemis',
 'pengemis',
 'mengemis',
 'menyesatkan',
 'belabor',
 'terlewat',
 'mengepung',
 'mendustakan',
 'memperkecilkan',
 'memperkecilkan',
 'memperkecilkan',
 'yg suka berperang',
 'suka berperang',
 'berperang',
 'belligerently',
 'meratapi',
 'mengeluh',
 'kaget',
 'bengkok',
 'mencaci',
 'bereave',
 'perkabungan',
 'gila',
 'mengamuk',
 'minta dengan sangat',
 'dilanda',
 'mengepung',
 'menjelekkan',
 'bestial',
 'mengkhianati',
 'pengkhianatan',
 'pengkhianatan',
 'pengkhianat',
 'mengkhianati',
 'mengkhianati',
 'meratapi',
 'berhati-hati',
 'membingungkan',
 'bingung',
 'membingungkan',
 'bewilderingly',
 'kebingungan',
 'menyihir',
 'berat sebelah',
 'berat sebelah',
 'berat sebelah',
 'cekcok',
 'pertelingkahan',
 'tipuan bida',
 'bigotries',
 'ketaksuban',
 'jalang',
 'bitchy',
 'menggigit',
 'bitingly',
 'pahit',
 'keras',
 'kepahitan',
 'pelik',
 'pengobrol',
 'pengobrol',
 'ugut',
 'blah',
 'menyalahkan',
 'patut disalahkan',
 'hambar',
 'blandish',
 'menghujat',
 'menghujat',
 'kekufuran',
 'diletupkan',
 'terang-terangan',
 'terang-terangan',
 'ngobrol',
 'suram',
 'bleakly',
 'rasa suram',
 'berdarah',
 'berdarah',
 'berdarah',
 'cacat cela',
 'buta',
 'pembutaan',
 'blindingly',
 'sisi buta',
 'lepuh',
 'melepuh',
 'kembung',
 'tersumbat',
 'orang bodoh',
 'pertumpahan darah',
 'dahagakan darah',
 'berdarah',
 'Bernoda kotor',
 'tamparan',
 'kesilapan',
 'blundering',
 'kesilapan',
 'tumpul',
 'kabur',
 'bluring',
 'kabur',
 'kabur',
 'kabur',
 'mengaburkan',
 'berkata tanpa berpikir',
 'bermegah-megah',
 'meragukan',
 'palsu',
 'didih',
 'didih',
 'riuh',
 'bom',
 'membedil',
 'pengeboman',
 'besar mulut',
 'perhambaan',
 'gila',
 'bore',
 'bosan',
 'kebosanan',
 'gerek',
 'membosankan',
 'memperbaiki kurang baik',
 'mengganggu',
 'peduli',
 'mengganggu',
 'merunsingkan',
 'menyusahkan',
 'bowdlerize',
 'boikot',
 'braggart',
 'bragger',
 'bodoh',
 'brainwash',
 'kurang ajar',
 'brashly',
 'kelancangan',
 'brat',
 'kesombongan',
 'kurang ajar',
 'brazenly',
 'brazenness',
 'melanggar',
 'percutian',
 'putus',
 'break-up',
 'rosak',
 'berbuka',
 'rehat',
 'putus',
 'breakups',
 'rasuah',
 'belerang',
 'bulu',
 'rapuh',
 'memecahkan',
 'patah',
 'hati yang terluka',
 'brood',
 'menakuti',
 'lebam',
 'lebam',
 'lebam',
 'lebam',
 'brusque',
 'kejam',
 'brutalizing',
 'kekejaman',
 'kekejaman',
 'membengisi',
 'brutalizing',
 'kejam',
 'brute',
 'orang dungu',
 'bs',
 'buckle',
 'bug',
 'bugging',
 'buggy',
 'bug',
 'bulkier',
 'kebesaran',
 'besar',
 'bulkyness',
 'bull ****',
 'lembu ----',
 'pembuli',
 'tahi',
 'bullshyt',
 'pembuli',
 'buli',
 'bullyingly',
 'bum',
 'bertemu',
 'terserempak',
 'menghentam',
 'bumpping',
 'lebam',
 'berbonggol',
 'mengerjakan dgn kurang baik',
 'pekerja buruk',
 'diintai',
 'dua tingkat',
 'beban',
 'membebankan',
 'burdensomely',
 'membakar',
 'dibakar',
 'pembakaran',
 'terbakar',
 'dada',
 'hiasan arca',
 'penyibuk',
 'daging',
 'penyembelihan besar-besaran',
 'dengung',
 'Byzantine',
 'tertawa kecil',
 'bencana',
 'yg merugikan',
 'calamitously',
 'bencana',
 'kapalan',
 'mengumpat',
 'umpat',
 'fitnah',
 'memfitnah',
 'calumniously',
 'umpatan',
 'kanser',
 'kanser',
 'kanibal',
 'mengalih',
 'menyerah',
 'berubah-ubah',
 'capriciously',
 'ketidakteraturan',
 'karam',
 'cuai',
 'kecuaian',
 'karikatur',
 'pembunuhan beramai-ramai',
 'kap',
 'kartun',
 'tunai kekurangan uang',
 'memberi hukuman berat',
 'dikembiri',
 'mangsa',
 'bencana',
 'cataclysmal',
 'bencana',
 'cataclysmically',
 'malapetaka',
 'bencana',
 'bencana',
 'catastrophically',
 'bencana yang melanda',
 'kaustik',
 'caustically',
 'amaran',
 'gua',
 'celaan',
 'melecetkan',
 'sekam',
 'mengecewakan',
 'mencabar',
 'huru-hara',
 'huru-hara',
 'menghukum',
 'mengazab',
 'azab',
 'perbualan',
 'chatterbox',
 'murah',
 'memurahkan',
 'murah',
 'menipu',
 'ditipu',
 'penipu',
 'menipu',
 'menipu',
 'berkotak-kotak',
 'kebahagiaan',
 'cheesy',
 'mencaci',
 'kebudak-budakan',
 'sejuk',
 'sejuk',
 'chintzy',
 'pencekik',
 'mudah tersinggung',
 'bergelora',
 'kerja rumah',
 'kronik',
 'chunky',
 'teriak',
 'riuh',
 'pertembungan',
 'klise',
 'klise',
 'clique',
 'menyumbat',
 'tersumbat',
 'terompah',
 'awan',
 'kekaburan',
 'mendung',
 'keliru dengan konsep',
 'kekok',
 'clunky',
 'kasar',
 'sombong',
 'memaksa',
 'paksaan',
 'paksaan',
 'sejuk',
 'dgn tdk ramah',
 'runtuh',
 'berpakat',
 'pakatan sulit',
 'agresif',
 'terbakar',
 'lucu',
 'simpati',
 'perkara biasa',
 'kekecohan',
 'kegemparan',
 'leka',
 'mengadu',
 'merungut',
 'mengadu',
 'mengadu',
 'aduan',
 'aduan',
 'kompleks',
 'rumit',
 'komplikasi',
 'bersubahat',
 'paksaan',
 'kompulsif',
 'mengalah',
 'mengakui',
 'keangkuhan',
 'sombong',
 'pemusatan',
 'concens',
 'kebimbangan',
 'mengambil berat',
 'kebimbangan',
 'konsesi',
 'konsesi',
 'mengutuk',
 'keji',
 'kutukan',
 'mengutuk',
 'mengutuk',
 'berkenan',
 'condescending',
 'sombong',
 'sikap melindungi',
 'mengaku',
 'pengakuan',
 'pengakuan',
 'terhad',
 'konflik',
 'konflik',
 'bercanggah',
 'konflik',
 'memalukan',
 'digagalkan',
 'membaurkan',
 'menghadapi',
 'konfrontasi',
 'konfrontasi',
 'mengelirukan',
 'keliru',
 'mengelirukan',
 'mengelirukan',
 'kekeliruan',
 'kekeliruan',
 'sesak',
 'kesesakan',
 'keburukan',
 'conscons',
 'konservatif',
 'mudah dilihat',
 'mudah dilihat',
 'konspirasi',
 'konspirasi',
 'konspirator',
 'konspirasi',
 'bersubahat',
 'kebingungan',
 'berjangkit',
 'mencemarkan',
 'tercemar',
 'pencemaran bahan',
 'mencemarkan',
 'pencemaran',
 'penghinaan',
 'hina',
 'menghina',
 'menghina',
 'berdepan',
 'perdebatan',
 'perbalahan',
 'merubah bentuk',
 'contortions',
 'bercanggah',
 'percanggahan',
 'bercanggah',
 'sifat keras',
 'melanggar',
 'jayakan',
 'tersusun',
 'kontroversi',
 'kontroversi',
 'berbelit',
 'mengakis',
 'kakisan',
 'corrosions',
 'menghakis',
 'rasuah',
 'rosak',
 'merosakkan',
 'rasuah',
 'merosakkan',
 'corruptted',
 'mahal',
 'mahal',
 'tidak produktif',
 'tidak produktif',
 'coupists',
 'tamak',
 'pengecut',
 'pengecut',
 'pemarah',
 'retak',
 'retak',
 'retak',
 'dgn licin',
 'craftly',
 'licik',
 'kejang',
 'sempit',
 'kekejangan',
 'dongkol',
 'crap',
 'buruk sekali',
 'craps',
 'kemalangan',
 'terhempas',
 'kemalangan',
 'terhempas',
 'crass',
 'pengecut',
 'cravenly',
 'kegilaan',
 'crazily',
 'kegilaan',
 'gila',
 'berderak',
 'berderit',
 'creaks',
 'mudah percaya',
 'rayapan',
 'menjalar',
 'gigil',
 'menyeramkan',
 'merangkak',
 'jenayah',
 'jenayah',
 'merasa jijik',
 'Sukar untuk dibayangkan',
 'cringes',
 'melumpuhkan',
 'lumpuh',
 'cripples',
 'melumpuhkan',
 'krisis',
 'pengkritik',
 'kritikal',
 'kritikan',
 'kritikan',
 'mengkritik',
 'mengkritik',
 'mengkritik',
 'pengkritik',
 'kronisme',
 'penjahat',
 'bengkok',
 'Crooks',
 'sesak',
 'kesesakan',
 'mentah',
 'kejam',
 'crueler',
 'cruelest',
 'kejam',
 'cruelness',
 'kekejaman',
 'kekejaman',
 'runtuh',
 'runtuh',
 'yg tdk memuaskan',
 'remuk',
 'renyuk',
 'crumples',
 'hancur',
 'dihancurkan',
 'menghancurkan',
 'menangis',
 'tanpa niat',
 'pelakunya',
 'rumit',
 'kemaluan wanita',
 'Cunts',
 'cuplrit',
 'laknat',
 'sumpahan',
 'kutukan',
 'kurang sopan',
 'makian',
 'keras kepala',
 'kejam',
 'sinis',
 'sinis',
 'd * mn',
 'kerosakan',
 'rosak',
 'ganti rugi',
 'merosakkan',
 'sialan',
 'terkutuk',
 'mengerikan',
 'kutukan',
 'terkutuk',
 'memberatkan',
 'peredam',
 'bahaya',
 'berbahaya',
 'dangerousness',
 'gelap',
 'gelap',
 'gelap',
 'gelap',
 'kegelapan',
 'pengecut yg kejam',
 'pengecut',
 'menghilangkan semangat',
 'menakutkan',
 'dauntingly',
 'berlengah-lengah',
 'kebingungan',
 'mimpi',
 'mati',
 'deadbeat',
 'kebuntuan',
 'maut',
 'berat muatan',
 'pekak',
 'kekurangan',
 'kematian',
 'kejatuhan',
 'menghina',
 'kehinaan',
 'Debaser',
 'dibahaskan',
 'melacurkan',
 'debaucher',
 'perbuatan yang songsang',
 'melemahkan',
 'melemahkan',
 'kelesuan',
 'hutang',
 'hutang',
 'keruntuhan',
 'picisan',
 'pereputan',
 'reput',
 'penipuan',
 'penipu',
 'berpura-pura',
 'tipu daya',
 'memperdaya',
 'penipu',
 'penipu',
 'menipu',
 'penipuan',
 'mengelirukan',
 'nampak',
 'mendeklamasikan',
 'penurunan',
 'penurunan',
 'menurun',
 'susutan',
 'rungkuh',
 'kelemahan karena usia tua',
 'mengutuk',
 'fitnah',
 'fitnah',
 'fitnah',
 'memfitnah',
 'kecacatan',
 'rosak',
 'kecacatan',
 'pertahanan',
 'tantangan',
 'ingkar',
 'tangan yang dinaikkan,',
 'kekurangan',
 'kekurangan',
 'kekurangan',
 'menajiskan',
 'Defiler',
 'berubah bentuk',
 'cacat',
 'menipu',
 'tidak berfungsi lagi',
 'menentang',
 'merosot',
 'degenerately',
 'degenerasi',
 'degradasi',
 'merendahkan',
 'menjatuhkan maruah',
 'degradingly',
 'dehumanization',
 'menyahinsanikan',
 'berkenan',
 'mematahkan semangat',
 'kecewa',
 'muka masam mencuka',
 'kepatahan',
 'kelewatan',
 'ditangguhkan',
 'melambatkan',
 'kelewatan',
 'kenakalan',
 'delinkuen',
 'tergila-gila',
 'kecelaruan',
 'menipu',
 'terpedaya',
 'banjir',
 'angan-angan',
 'delusional',
 'khayalan',
 'merendahkan',
 'merendahkan martabat',
 'kematian',
 'merobohkan',
 'pembongkar',
 'setan',
 'iblis',
 'memburuk-burukkan',
 'syaitan',
 'demonizes',
 'memburuk-burukkan',
 'melemahkan semangat',
 'mematahkan semangat',
 'demoralizingly',
 'penafian',
 'menafikan',
 'menafikan',
 'memfitnah',
 'mengutuk',
 'padat',
 'penyok',
 'kemek',
 'penyok',
 'denunciate',
 'kecaman',
 'mengecam',
 'menafikan',
 'menafikan',
 'mengurangkan',
 'amat dikesali',
 'deplorably',
 'kesal',
 'menyesali',
 'deploringly',
 'merusak akhlak',
 'berakhlak buruk',
 'depravedly',
 'mengutuk',
 'tertekan',
 'tertekan',
 'menyedihkan',
 'depressingly',
 'kemurungan',
 'lekukan',
 'melucutkan',
 'dilucutkan',
 'mengejek',
 'ejekan',
 'bersifat olok-olok',
 'mengejek',
 'derisiveness',
 'menghina',
 'merosakkan',
 'padang pasir',
 'pembelotan',
 'mengeringkan',
 'desiccated',
 'desititute',
 'sepi',
 'desolately',
 'ketandusan',
 'putus asa',
 'berputus asa',
 'despairingly',
 'terdesak',
 'sangat-sangat',
 'terdesak',
 'keji',
 'despicably',
 'menghina',
 'hina',
 'despoiler',
 'kepatahan',
 'kesedihan',
 'gundah gulana',
 'despondently',
 'zalim',
 'zalim',
 'kezaliman',
 'ketidakstabilan',
 'destains',
 'melarat',
 'melarat',
 'memusnahkan',
 'pemusnah',
 'kemusnahan',
 'merosakkan',
 'tanpa sistem',
 'menghalang',
 'merosot',
 'semakin merosot',
 'kemerosotan',
 'penghalang',
 'benci',
 'keji',
 'detestably',
 'dibenci',
 'detesting',
 'membenci',
 'mengurangkan',
 'detracted',
 'mengurangi',
 'umpatan',
 'detracts',
 'merugikan',
 'memudaratkan',
 'membinasakan',
 'musnah',
 'merana',
 'dahsyat',
 'Meluluhkan',
 'kehancuran',
 'menyimpang',
 'sisihan',
 'syaitan',
 'jahat',
 'devilishly',
 'perbuatan jahat',
 'devilry',
 'licik',
 'deviously',
 'deviousness',
 'tanpa',
 'sangat jahat',
 'kejam',
 'diabolically',
 'bertentangan',
 'diappointed',
 'serangan kata-kata',
 'diatribes',
 'batang',
 'diktator',
 'diktator',
 'mati',
 'mati-keras',
 'meninggal dunia',
 'mati',
 'sukar',
 'kesukaran',
 'kesukaran',
 'sifat malu-malu',
 'usang',
 'dilema',
 'berlengah-lengah',
 'malap',
 'dimmer',
 'din',
 'ding',
 'dings',
 'imut',
 'mengerikan',
 'direly',
 'direness',
 'kotoran',
 'Dirtbag',
 'dirtbags',
 'dirts',
 'kotor',
 'melumpuhkan',
 'kurang upaya',
 'menyelisihkan',
 'kelemahan',
 'yang kurang bernasib baik',
 'merugikan',
 'kelemahan',
 'disaffect',
 'setia',
 'mungkir',
 'tidak bersetuju',
 'marah-marah',
 'disagreeably',
 'tidak bersetuju',
 'tidak bersetuju',
 'perbezaan pendapat',
 'tidak bersetuju',
 'tidak membenarkan',
 'disapointed',
 'disapointing',
 'disapointment',
 'mengecewakan',
 'kecewa',
 'mengecewakan',
 'mengecewakan',
 'kekecewaan',
 'kekecewaan',
 'mengecewakan',
 'kutukan',
 'penolakan',
 'menolak',
 'meluluskan',
 'melucutkan senjata',
 'kekusutan',
 'bencana',
 'disasterous',
 'bencana',
 'malapetaka',
 'menyangkal',
 'Ttg',
 'kekafiran',
 'kafir',
 'kafir',
 'menafikan',
 'discombobulate',
 'membingungkan',
 'discomfititure',
 'ketidakselesaan',
 'discompose',
 'menggelisahkan',
 'malu-malu',
 'membingungkan',
 'disconcertingly',
 'putus asa',
 'disconsolately',
 'disconsolation',
 'rasa tidak puas hati',
 'tidak puas hati',
 'tdk senang',
 'dihentikan',
 'ketakselanjaran',
 'tidak berterusan',
 'perpecahan',
 'perselisihan',
 'sumbang',
 'tdk',
 'tidak menggalakkan',
 'semangat',
 'tidak menggalakkan',
 'discouragingly',
 'discourteous',
 'discourteously',
 'discoutinous',
 'menjatuhkan',
 'bercanggah',
 'mendiskriminasi',
 'diskriminasi',
 'diskriminasi',
 'penghinaan',
 'menghina',
 'enggan beribadat kepada Allah',
 'disdainfully',
 'tdk setuju',
 'kehinaan',
 'terhina',
 'memalukan',
 'memalukan',
 'memarahkan',
 'tidak puas hati',
 'jijik',
 'jijik',
 'disgustedly',
 'menjijikkan',
 'disgustfully',
 'menjijikkan',
 'disgustingly',
 'mengecilkan hati',
 'mengecewakan',
 'dishearteningly',
 'tidak jujur',
 'curang',
 'kecurangan',
 'kehinaan',
 'hina',
 'dishonorablely',
 'kekecewaan',
 'kecewa',
 'kekecewaan',
 'disillusions',
 'rasa benci',
 'segan',
 'jujur',
 'disingenuously',
 'hancur',
 'hancur',
 'hancur',
 'perpecahan',
 'tidak berminat',
 'tidak berminat',
 'suka',
 'Tidak disukai',
 'suka',
 'tidak suka',
 'terkehel',
 'tidak setia',
 'tidak setia',
 'suram',
 'dismally',
 'dismalness',
 'kecewa',
 'kecewa',
 'dismaying',
 'dismayingly',
 'acuh',
 'dismissively',
 'maksiat',
 'taat',
 'menderhaka',
 'disoobedient',
 'gangguan',
 'bercelaru',
 'senonoh',
 'tidak teratur',
 'disorient',
 'keliru',
 'berlepas diri',
 'memperkecilkan',
 'menghina',
 'meremehkan',
 'tdk diperlukan',
 'dispirit',
 'putus asa',
 'dispiritedly',
 'melemahkan semangat',
 'menggantikan',
 'pelarian',
 'tdk menyenangkan',
 'senang',
 'memualkan',
 'tidak berpuas hati',
 'tidak seimbang',
 'menyangkal',
 'dipertikaikan',
 'pertikaian',
 'dipertikaikan',
 'membimbangkan',
 'membimbangkan',
 'disquietingly',
 'keyakinannya',
 'tidak mengambil kira',
 'disregardful',
 'keji',
 'mendapat nama buruk',
 'tidak menghormati',
 'disrespectable',
 'disrespectablity',
 'tidak menghormati',
 'tidak hormat',
 'disrespectfulness',
 'tidak menghormati',
 'mengganggu',
 'gangguan',
 'menimbulkan gangguan',
 'diss',
 'kecewa',
 'dissappointed',
 'dissappointing',
 'rasa tidak puas hati',
 'tidak memuaskan',
 'tidak berpuas hati',
 'dissatisfies',
 'rasa tdk puas hati',
 'tidak memuaskan',
 'dissed',
 'pura-pura',
 'pura-pura',
 'pertengkaran',
 'perbezaan pendapat',
 'ingkar',
 'dissention',
 'merugikan',
 'disses',
 'penentangan',
 'pembangkang',
 'penentang',
 'dissing',
 'dissocial',
 'bermoral',
 'pembubaran',
 'percanggahan',
 'tdk sesuai',
 'dissonantly',
 'menghalang',
 'menasihati jangan',
 'distains',
 'kebencian',
 'hina',
 'distastefully',
 'memutarbelitkan',
 'diputarbelitkan',
 'penyelewengan',
 'menggalakkan,',
 'mengalihkan perhatian',
 'mengganggu',
 'gangguan',
 'tertekan',
 'distraughtly',
 'distraughtness',
 'kesusahan',
 'bermasalah',
 'menyedihkan',
 'distressingly',
 'kesangsian',
 'curiga',
 'distrusting',
 'mengganggu',
 'gangguan',
 'terganggu',
 'membimbangkan',
 'membimbangkan',
 'perpecahan',
 'disvalue',
 'berbeza',
 'memecah-belahkan',
 'divisively',
 'pecah belah',
 'dizzing',
 'dizzingly',
 'pening',
 'yg menggigil',
 'dodgey',
 'mantap',
 'doggedly',
 'dogmatik',
 'belenggu',
 'bertindak seperti orang berkuasa',
 'bersifat menguasai dgn keras',
 'donside',
 'azab',
 'ditakdirkan',
 'kiamat',
 'dadah',
 'keraguan',
 'ragu',
 'kuatir',
 'keraguan',
 'orang yang keji',
 'douchebag',
 'Douchebags',
 'pembukaan lagu',
 'tunduk malu',
 'Downer',
 'kehancuran',
 'downfallen',
 'penurunan',
 'rendah hati',
 'downheartedly',
 'turun bukit',
 'Kelemahan',
 'kelemahan',
 'kelembapan',
 'kemerosotan',
 'membosankan',
 'zalim',
 'draconic',
 'drag',
 'diseret',
 'mengheret',
 'Dragoon',
 'Penarik',
 'mengalirkan',
 'bersaliran',
 'penyaliran',
 'longkang',
 'drastik',
 'secara drastik',
 'kelemahan',
 'kelemahan',
 'takut',
 'mengerikan',
 'teruk',
 'dreadfulness',
 'suram',
 'menitis',
 'menitis',
 'drippy',
 'menitis',
 'Drone',
 'terasa berat',
 'droops',
 'tercicir',
 'tercicir',
 'tercicir',
 'keciciran',
 'kemarau',
 'lemas',
 'mabuk',
 'pemabuk',
 'mabuk',
 'meragukan',
 'dubiously',
 'dubitable',
 'tak berguna',
 'membosankan',
 'orang bodoh',
 'bisu',
 'mengherankan',
 'pembuangan',
 'dibuang',
 'lambakan',
 'tempat pembuangan sampah',
 'orang bodoh',
 'penjara',
 'kurungan bawah tanah',
 'mencurangi',
 'debu',
 'berdebu',
 'semakin berkurangan',
 'mati',
 'earsplitting',
 'aneh',
 'kesipian',
 'patung',
 'kelancangan',
 'egosentrik',
 'egomania',
 'keegoan',
 'egois',
 'egotistically',
 'mengerikan',
 'benar-benar',
 'pemilihan rigger',
 'penghapusan',
 'kurus',
 'melemahkan',
 'memalukan',
 'memalukan',
 'malu',
 'rasa malu',
 'embattled',
 'menengkarkan',
 'terlibat',
 'tengkar',
 'kecemasan',
 'tegas',
 'tegas',
 'kekosongan',
 'menceroboh',
 'pencerobohan',
 'membahayakan',
 'musuh',
 'musuh',
 'melemaskan',
 'melemaskan',
 'enflame',
 'menelan',
 'menyuruh',
 'permusuhan',
 'menimbulkan sakit hati',
 'marah',
 'enraging',
 'menghambakan',
 'menjerut',
 'tersangkut',
 'memerangkap',
 'pemerangkapan',
 'iri hati',
 'enviously',
 'enviousness',
 'wabak',
 'yg mempunyai dua arti',
 'padam',
 'menghakis',
 'menghakis',
 'hakisan',
 'err',
 'ingkar',
 'tidak menentu',
 'erratically',
 'salah',
 'tersilap',
 'ralat',
 'kesilapan',
 'letusan',
 'escapade',
 'menjauhinya',
 'estranged',
 'mengelakkan',
 'pengelakan',
 'mengelak',
 'jahat',
 'orang yang berbuat jahat',
 'kejahatan',
 'mengeviserat',
 'memburukkan lagi',
 'exagerate',
 'exagerated',
 'exagerates',
 'membesar-besarkan',
 'keterlaluan',
 'menyakiti hati',
 'geram',
 'menjengkelkan',
 'exasperatingly',
 'geram',
 'berlebihan',
 'berlebihan',
 'pengecualian',
 'mencela',
 'menyeksa',
 'luar biasa',
 'alasan',
 'alasan',
 'merasa jijik',
 'ekzos',
 'habis',
 'keletihan',
 'ekzos',
 'exhorbitant',
 'Nasihatilah',
 'buangan',
 'terlalu tinggi',
 'exorbitantance',
 'exorbitantly',
 'mengusir',
 'mahal',
 'tamat',
 'tamat tempoh',
 'meletup',
 'mengeksploitasi',
 'eksploitasi',
 'letupan',
 'merampas',
 'rampasan',
 'expulse',
 'memadamkan',
 'menghapuskan',
 'penghapusan',
 'memadamkan',
 'memeras',
 'peras ugut',
 'luaran',
 'berlebih-lebihan',
 'boros',
 'batas',
 'ekstremisme',
 'pelampau',
 'pelampau',
 'yg buruk',
 'f ** k',
 'memalsukan',
 'fabrikasi',
 'jenaka',
 'dgn jenaka',
 'gagal',
 'gagal',
 'gagal',
 'gagal',
 'kegagalan',
 'kegagalan',
 'pengsan',
 'pengecut',
 'pengkhianat',
 'palsu',
 'jatuh',
 'kesilapan',
 'banyak kesalahan',
 'fallaciously',
 'fallaciousness',
 'anggapan yang salah',
 'tumbang',
 'jatuh',
 'gugur',
 'jatuh',
 'SALAH',
 'kepalsuan',
 'palsu',
 'memalsukan',
 'terputus-putus',
 'gerun',
 'kelaparan',
 'lapar',
 'fanatik',
 'fanatik',
 'fanatik',
 'fanatik',
 'fanatik',
 'khayalan',
 'dibuat-buat',
 'sandiwara',
 'melucukan',
 'melucukan-lagi-provokatif',
 'farcically',
 'farfetched',
 'fasisme',
 'fasis',
 'pemilih',
 'fastidiously',
 'fastuous',
 'lemak',
 'kucing gemuk',
 'lemak kucing',
 'maut',
 'takdir',
 'fatalistically',
 'parah',
 'kucing gemuk',
 'fatcats',
 'malang',
 'fatefully',
 'tidak dapat diukur',
 'keletihan',
 'penat',
 'fatique',
 'lemak',
 'kebodohan',
 'bodoh',
 'secara bodoh',
 'kesalahan',
 'kesalahan',
 'rosak',
 'fawningly',
 'faze',
 'ketakutan',
 'takut',
 'dahsyat',
 'kebimbangan',
 'menakutkan',
 'tak berguna',
 'lemah',
 'feeblely',
 'berfikiran lemah',
 'berpura-pura',
 'kepura-puraan',
 'jatuh',
 'penjahat',
 'jahat',
 'matian',
 'keganasan',
 'busuk',
 'demam',
 'demam',
 'demam',
 'kemelut',
 'berbohong',
 'fibber',
 'berubah-ubah',
 'fiksyen',
 'fiksyen',
 'rekaan',
 'orang yg tdk tenang',
 'resah',
 'orang yg sangat jahat',
 'sangat jahat',
 'sengit',
 'boneka',
 'najis',
 'kotor',
 'memperdaya',
 'cerewet',
 'rekahan',
 'penumbuk',
 'sangat menakjubkan',
 'ternganga keheranan',
 'menandai',
 'terang-terangan',
 'flagrantly',
 'bakat',
 'Flairs',
 'kritikan',
 'mengelupas',
 'flakey',
 'flakieness',
 'mengelupas',
 'tidak stabil',
 'suar',
 'suar',
 'marah',
 'flareups',
 'rata keluar',
 'Konserto',
 'kecacatan',
 'cacat',
 'kelemahan',
 'melarikan diri',
 'fleed',
 'melarikan diri',
 'pandangan yg menghina',
 'melarikan diri',
 'sekejap',
 'flicering',
 'kerlipan',
 'kelipan',
 'kelipan',
 'flighty',
 'penipu',
 'rapuh',
 'flirt',
 'genit',
 'Lhasa',
 'menggelepar',
 'floundering',
 'melanggar',
 'membingungkan',
 'musuh',
 'menipu',
 'tertipu',
 'membabi buta',
 'bodoh',
 'bodoh',
 'kebodohan',
 'melarang',
 'dilarang',
 'melarang',
 'secara paksa',
 'firasat',
 'forebodingly',
 'kehilangan',
 'palsu',
 'pelupa',
 'forgetfully',
 'kealpaan',
 'kesepian',
 'forlornly',
 'meninggalkan',
 'meninggalkan',
 'bersumpah untuk meninggalkan',
 'busuk',
 'secara khianat',
 'kekotoran',
 'marah-marah',
 'fractiously',
 'patah',
 'rapuh',
 'berpecah-belah',
 'lemah',
 'terburu-buru',
 'dgn penuh ketakutan',
 'franticly',
 'penipuan',
 'penipuan',
 'penuh',
 'Kelelahan',
 'frazzled',
 'lain daripada yang lain',
 'freaking',
 'ganjil',
 'freakishly',
 'mengangkat tema',
 'membekukan',
 'membeku',
 'pembekuan',
 'fanatik',
 'frenetically',
 'penuh kegilaan',
 'kegilaan',
 'fret',
 'jengkel',
 'frets',
 'geseran',
 'perbalahan',
 'goreng',
 'friggin',
 'frigging',
 'ketakutan',
 'menakutkan',
 'menakutkan',
 'tampak',
 'ngeri',
 'menakuntukan',
 'dingin',
 'fros',
 'berkerut',
 'beku',
 'beku',
 'sia-sia',
 'fruitlessly',
 'menggagalkan',
 'kecewa',
 'amat menggusarkan',
 'mengecewakan',
 'frustratingly',
 'kekecewaan',
 'kekecewaan',
 'fuck',
 'fucking',
 'fudge',
 'pelarian',
 'besar-besaran',
 'mencaci',
 'meraba-raba',
 'wasap',
 'wasap',
 'fundamentalisme',
 'funky',
 'dgn lucu',
 'lucu',
 'marah',
 'marah',
 'kemarahan',
 'kemarahan',
 'kekecohan',
 'cerewet',
 'memukul dgn tongkat',
 'basi',
 'sia-sia',
 'futilely',
 'sia-sia',
 'kabur',
 'omongan',
 'taji',
 'gaffe',
 'menyangkal',
 'gainsayer',
 'hempedu',
 'galling',
 'gallingly',
 'galls',
 'gangster',
 'menganga',
 'sampah',
 'menonjol',
 'GASP',
 'gauche',
 'terlalu menonjol',
 'menganga',
 'gawky',
 'nenek',
 'pembunuhan beramai-ramai',
 'menjadi kaya',
 'mengerikan',
 'ghetto',
 'ghosting',
 'cara bicara',
 'raban',
 'hinaan',
 'pening',
 'gimik',
 'gimmicked',
 'gimmicking',
 'gimik',
 'menarik perhatian',
 'silau',
 'dgn berkilau',
 'fasih',
 'dgn fasih',
 'akibat gangguan',
 'glitches',
 'gloatingly',
 'kesuraman',
 'suram',
 'pandangan marah',
 'suram',
 'lebihan',
 'menggigit',
 'menghalau',
 'goading',
 'tuhan-seksa yang amat besar',
 'orang bodoh',
 'bodoh',
 'teruskan',
 'gosip',
 'yg tak tahu malu',
 'gracelessly',
 'rasuah',
 'berbintik',
 'bergelut',
 'menjengkelkan',
 'grating',
 'sungguh-sungguh',
 'berminyak',
 'ketamakan',
 'tamak',
 'kesedihan',
 'rungutan',
 'rasa tidak puas hati',
 'bersedih hati',
 'bersedih',
 'parah',
 'parah',
 'suram',
 'berkerut',
 'mengisar',
 'mengomel',
 'gripes',
 'mengerikan',
 'cekal',
 'kasar',
 'terlalu',
 'menjijikkan',
 'merengus',
 'cepat marah',
 'berasas',
 'masalahnya',
 'menggeram',
 'dendam',
 'dendam',
 'karena dengki',
 'enggan',
 'mengerikan',
 'gruesomely',
 'suram',
 'ngomel',
 'grumpier',
 'grumpiest',
 'grumpily',
 'grumpish',
 'pemarah',
 'tipu daya',
 'bersalah',
 'dgn perasaan bersalah',
 'bersalah',
 'mudah tertipu',
 'gutless',
 'longkang',
 'hack',
 'hacks',
 'lesu',
 'tawar-menawar',
 'keguguran rambut',
 'halfhearted',
 'separuh hati',
 'menderita khayalan',
 'halusinasi',
 'menghalang',
 'menghalang',
 'cacat',
 'hang',
 'tergantung',
 'tidak teratur',
 'malang',
 'pidato panjang dan tajam',
 'mengganggu',
 'diganggu',
 'mengganggu',
 'gangguan',
 'mendapat perlindungan',
 'pelabuhan',
 'keras',
 'hard-hit',
 'garis keras',
 'hard-liner',
 'hardball',
 'keras',
 'keras',
 'keras kepala',
 'keras hati',
 'hardliner',
 'hardliners',
 'kesusahan',
 'kesusahan',
 'bahaya',
 'dirosakkan',
 'berbahaya',
 'kemudaratan',
 'perampas',
 'perempuan jahanam',
 'diganggu',
 'harrow',
 'keras',
 'dengan keras;',
 'hasseling',
 'mudah',
 'diganggu',
 'bersusah-payah',
 'tergesa-gesa',
 'tergesa-gesa',
 'terburu-buru',
 'benci',
 'membenci',
 'kebencian',
 'hatefully',
 'hatefulness',
 'pembenci',
 'pembenci',
 'dibenci',
 'membenci',
 'kebencian',
 'sombong',
 'sombong',
 'menghantui',
 'memburu',
 'malapetaka',
 'agresif',
 'menjadi gila',
 'bahaya',
 'berbahaya',
 'jerebu',
 'berjerebu',
 'kepala sakit',
 'sakit kepala',
 'sakit kepala',
 'heartbreaker',
 'menyayat hati',
 'heartbreakingly',
 'kejam',
 'kafir',
 'berat tangan',
 'heavyhearted',
 'palang pintu',
 'menggoda',
 'dicela',
 'heckles',
 'sibuk',
 'lindung nilai',
 'hedonistik',
 'lalai',
 'besar',
 'hegemonism',
 'hegemonistic',
 'hegemoni',
 'kejam',
 'neraka',
 'tdk berhati-hati',
 'anak nakal',
 'neraka',
 'tidak berdaya',
 'berdaya',
 'tidak berdaya',
 "bid'ah",
 'bidaah',
 'bidaah',
 'teragak-agak',
 'hestitant',
 'mengerikan',
 'hideously',
 'hideousness',
 'high-priced',
 'hiliarious',
 'menghalang',
 'penghalang',
 'desis',
 'hissed',
 'desiran',
 'ho-hum',
 'simpan',
 'penipuan',
 'pincang',
 'hogs',
 'berongga',
 'hoodium',
 'mendustai',
 'samseng',
 'harapan',
 'begitu bercampur',
 'putus asa',
 'gerombolan',
 'dahsyat',
 'horrendously',
 'dahsyat',
 'mengerikan',
 'ngeri',
 'terkejut',
 'ngeri',
 'mengerikan',
 'menakutkan',
 'horrifys',
 'tebusan',
 'bermusuhan',
 'permusuhan',
 'permusuhan',
 'hotbeds',
 'hothead',
 'cepat marah',
 'rumah hijau',
 'keangkuhan',
 'menjajakan',
 'hum',
 'lembap',
 'menghina',
 'menghina',
 'penghinaan',
 'bersenandung',
 'hung',
 'menyakiti',
 'hurted',
 'menyakitkan',
 'mencederakan',
 'menyakitkan',
 'hustler',
 'gembar-gembur',
 'hypocricy',
 'kepura-puraan',
 'munafik',
 'orang munafik',
 'hipokrit',
 'hipokrit',
 'histeria',
 'hysteric',
 'histeria',
 'hysterically',
 'serangan penyakit saraf',
 'idiocies',
 'kebodohan',
 'bodoh',
 'bodoh',
 'idiotically',
 'bodoh',
 'terbiar',
 'hina',
 'memalukan',
 'ignominiously',
 'kehinaan',
 'kejahilan',
 'jahil',
 'abai',
 'keliru',
 'sakit-mengandung',
 'tidak jelas',
 'sakit yang direka',
 'malang',
 'jelek',
 'sakit terbentuk',
 'kurang ajar',
 'sakit hati',
 'sakit-disusun',
 'sakit-marah',
 'sakit yang dirawat',
 'layanan buruk',
 'penggunaan sakit',
 'sakit digunakan',
 'menyalahi undang-undang',
 'secara haram',
 'tidak sah',
 'haram',
 'buta huruf',
 'penyakit',
 'tidak logik',
 'tidak logik',
 'tidak logik',
 'ilusi',
 'ilusi',
 'ilusi',
 'khayalan',
 'ketidakseimbangan',
 'dungu',
 'kemelut',
 'material',
 'tidak matang',
 'kesegeraan',
 'lama lagi',
 'bergerak',
 'tidak wajar',
 'immoderately',
 'sopan',
 'tidak bermoral',
 'tidak bermoral',
 'bermoral',
 'tak alih',
 'menjejaskan',
 'terjejas',
 'impasse',
 'sabar',
 'tidak sabar',
 'tidak sabar',
 'mencabar',
 'galangan',
 'menghalang',
 'halangan',
 'akan berlaku',
 'impenitent',
 'tidak sempurna',
 'ketidaksempurnaan',
 'ketidaksempurnaan',
 'tidak sempurna',
 'imperialis',
 'membahayakan',
 'angkuh',
 'imperiously',
 'tidak dibenarkan',
 'bersifat peribadi',
 'di luar pokok persoalan',
 'terburu-buru nafsu',
 'impetuously',
 'mukjizat',
 'meninggalkan kesan',
 'beriman',
 'kepala batu',
 'tidak masuk akal',
 'implausibly',
 'mengaitkan',
 'implikasi',
 'meledak',
 'kurang sopan',
 'tidak hormat',
 'tidak berfaedah',
 'yg mengganggu',
 'dgn sangat',
 'mengenakan',
 'imposers',
 'mengenakan',
 'pengenaan',
 'mustahil',
 'impossiblity',
 'mustahil',
 'mati pucuk',
 'memiskinkan',
 'miskin',
 'tidak praktikal',
 'menyumpah',
 'tidak tepat',
 'imprecisely',
 'ketakpersisan',
 'memenjarakan',
 'penjara',
 'ketidakmungkinan',
 'mustahil',
 'improbably',
 'tidak betul',
 'tidak wajar',
 'senonoh',
 'kelalaian',
 'kurang bijak',
 'kekasaran',
 'kurang ajar',
 'impudently',
 'meragukan',
 'impulsif',
 'gerak hati',
 'sewenang-wenangnya',
 'suci',
 'junub',
 'ketidakupayaan',
 'ketidaktepatan',
 'ketidaktepatan',
 'tidak tepat',
 'tidak tepat',
 'tidak bertindak',
 'tidak aktif',
 'kekurangan',
 'tidak mencukupi',
 'tidak cukup',
 'inadverent',
 'inadverently',
 'tidak digalakkan',
 'inadvisably',
 'bodoh',
 'inanely',
 'tidak sesuai',
 'tidak sesuai',
 'tdk tepat',
 'ketidakcakapan',
 'sukar berbicara',
 'tidak memberi perhatian sepenuhnya',
 'didengar',
 'tidak berupaya',
 'incapably',
 'tdk berhati-hati',
 'pembakar',
 'kemenyan',
 'tidak berhenti-henti',
 'tidak henti-henti',
 'menghasut',
 'hasutan',
 'ketidaksopanan',
 'buruk',
 'tdk',
 'tidak keruan',
 'tidak keruan',
 'incoherently',
 'tdk selaras',
 'tiada tandingan',
 'yang jauh',
 'incompatability',
 'ketidakserasian',
 'tidak serasi',
 'ketidakcekapan',
 'tidak cekap',
 'incompetently',
 'tidak lengkap',
 'incompliant',
 'difahami',
 'tdk dimengerti',
 'dibayangkan',
 'inconceivably',
 'tidak selaras',
 'incongruously',
 'Ngawur',
 'tidak penting',
 'inconsequentially',
 'inconsequently',
 'tidak bertimbang rasa',
 'inconsiderately',
 'tidak konsisten',
 'tidak konsisten',
 'ketidakselarasan',
 'tidak konsisten',
 'tdk dpt dihiburkan',
 'inconsolably',
 'tdk tetap',
 'kesulitan',
 'inconveniently',
 'tidak betul',
 'tidak betul',
 'tidak dapat diperbaiki',
 'incorrigibly',
 'amat tidak boleh dipercayai',
 'incredulously',
 'memupuk',
 'perbuatan yang keji',
 'tidak senonoh',
 'tidak sopan',
 'kebimbangan',
 'ragu-ragu',
 'indecisively',
 'ketidakpantasan',
 'tidak dapat dipertahankan',
 'tdk sopan',
 'tidak dapat ditentukan',
 'indeterminably',
 'tidak dapat ditentukan',
 'sikap acuh tak acuh',
 'acuh tak acuh',
 'miskin',
 'marah',
 'dgn memarahi',
 'kemarahan',
 'penghinaan',
 'yg tak dpt dibezakan',
 'tdk berhati-hati',
 'indiscreetly',
 'ketidakbijaksanaan',
 'sembarangan',
 'sewenang-wenangnya',
 'indiscriminating',
 'tidak dapat dibezakan',
 'mengindoktrinasi',
 'indoktrinasi',
 'malas',
 'memanjakan diri',
 'tidak berkesan',
 'tidak berkesan',
 'ketidakberkesanan',
 'tidak berkesan',
 'ineffectually',
 'ineffectualness',
 'tdk efisien',
 'ketidakmujarabannya',
 'ketidakcekapan',
 'tidak cekap',
 'tidak cekap',
 'sifat tdk bersemarak',
 'kaku',
 'tidak layak',
 'ineloquent',
 'ineloquently',
 'tidak cekap',
 'tindakan yg bodoh',
 'ineptly',
 'ketidaksamaan',
 'ketidaksamaan',
 'saksama',
 'inequitably',
 'ketidaksamaan',
 'tidak dapat dielakkan',
 'inescapably',
 'tdk penting',
 'tidak dapat dielakkan',
 'tidak dapat tidak',
 'dimaafkan',
 'inexcusably',
 'tidak dapat disekat',
 'dengan begitu',
 'kurang pengalaman',
 'tidak berpengalaman',
 'tdk',
 'inexpertly',
 'yg tak dpt diampuni',
 'inexplainable',
 'inextricable',
 'berkait',
 'terkenal',
 'infamously',
 'kehinaan',
 'dijangkiti',
 'jangkitan',
 'jangkitan',
 'rendah',
 'rendah diri',
 'berkenaan dgn neraka',
 'mengerumuni',
 'berkutu',
 'kafir',
 'kafir',
 'penyusup',
 'penyusup',
 'lemah',
 'membakar',
 'keradangan',
 'radang',
 'inflammed',
 'melambung',
 'inflasi',
 'fleksibel',
 'mengenakan',
 'pelanggaran',
 'melanggar',
 'pelanggaran',
 'pelanggaran',
 'menggeramkan',
 'marah',
 'menyebalkan',
 'infuriatingly',
 'hina',
 'orang yang kufur ingkar',
 'kekufuran',
 'menghalang',
 'perencatan',
 'ganas',
 'inhospitality',
 'tidak berperikemanusiaan',
 'tidak berperikemanusiaan',
 'kekejaman',
 'memudaratkan',
 'inimically',
 'zalim',
 'kesalahan',
 'Montage',
 'mencederakan',
 'memudaratkan',
 'kecederaan',
 'kezaliman',
 'ketidakadilan',
 'sindiran',
 'tidak beroperasi',
 'hell',
 'tamak haloba',
 'inordinately',
 'gila',
 'insanely',
 'gila',
 'tidak pernah puas',
 'tidak selamat',
 'tidak selamat',
 'nirakal',
 'tidak sensitif',
 'insensitively',
 'tidak sensitif',
 'berbahaya',
 'insidiously',
 'tidak penting',
 'tidak penting',
 'remeh-temeh',
 'tidak ikhlas',
 'insincerely',
 'tidak ikhlas',
 'menyindir',
 'insinuating',
 'sindiran',
 'insociable',
 'berlagak sombong',
 'sombong',
 'menderhaka',
 'solven',
 'keadaan acuh tak acuh',
 'ketidakstabilan',
 'instable',
 'menghasut',
 'penghasut',
 'penghasut',
 'ingkar perintah',
 'tdk kuat',
 'insubstantially',
 'tertahankan',
 'insufferably',
 'kekurangan',
 'tidak mencukupi',
 'tidak cukup',
 'sempit',
 'penghinaan',
 'menghina',
 'menghina',
 'insultingly',
 'penghinaan',
 'yg tdk berdasar',
 'insupportably',
 'tidak dapat diatasi',
 'insurmountably',
 'pemberontakan',
 'intefere',
 'inteferes',
 'tegang',
 'mengganggu',
 'gangguan',
 'boleh mengganggu',
 'terputus-putus',
 'mengganggu',
 'gangguan',
 'gangguan',
 'menakut-nakutkan',
 'menakutkan',
 'intimidatingly',
 'ugutan',
 'tertahan',
 'intolerablely',
 'intoleransi',
 'memabukkan',
 'sukar dikawal',
 'kedegilan',
 'keras kepala',
 'menceroboh',
 'pencerobohan',
 'mengganggu',
 'membanjiri',
 'dibanjiri',
 'penceroboh',
 'tidak sah',
 'membatalkan',
 'ilat',
 'invasif',
 'caci maki',
 'memujuk',
 'yg menyakitkan',
 'invidiously',
 'invidiousness',
 'tidak kelihatan',
 'secara sukarela',
 'sukarela',
 'bengkeng',
 'marah',
 'irately',
 'kemarahan',
 'menjengkelkan',
 'kesal,',
 'irking',
 'irks',
 'menyakitkan',
 'irksomely',
 'irksomeness',
 'irksomenesses',
 'ironis',
 'ironis',
 'ironinya',
 'ironi',
 'ironi',
 'irragularity',
 'tidak rasional',
 'irrationalities',
 'tidak rasional',
 'tidak rasional',
 'tak nisbah',
 'selari',
 'tidak boleh pulih',
 'irrecoverableness',
 'irrecoverablenesses',
 'irrecoverably',
 'tidak boleh tebus',
 'irredeemably',
 'irreformable',
 'tidak teratur',
 'ketidakteraturan',
 'tidak relevan',
 'tidak relevan',
 'boleh diperbaiki',
 'irreplacible',
 'tdk tertekan',
 'ragu-ragu',
 'tdk terurai',
 'tidak bertanggungjawab',
 'tidak bertanggungjawab',
 'irretating',
 'yg tak dpt ditebus',
 'tak boleh balik',
 'cepat marah',
 'irritably',
 'merengsa',
 'merengsakan',
 'jengkel',
 'menjengkelkan',
 'kerengsaan',
 'kegatalan',
 'mengasingkan',
 'terpencil',
 'pengasingan',
 'isu',
 'isu-isu',
 'gatal',
 'gatal-gatal',
 'gatal',
 'jabber',
 'letih',
 'bergerigi',
 'jem',
 'gemuruh',
 'berwarna kuning',
 'cemburu',
 'dgn hati-hati',
 'jealousness',
 'cemburu',
 'memperolokkan',
 'ejekan',
 'jeeringly',
 'ejekan',
 'menjejaskan',
 'bahaya',
 'jerk',
 'tersentak-sentak',
 'ketar',
 'kegelisahan',
 'gelisah',
 'pekerjaan-pembunuhan',
 'pengangguran',
 'jenaka',
 'joker',
 'sentakan',
 'judder',
 'juddering',
 'judders',
 'gelisah',
 'sampah',
 'junky',
 'tempat barang rongsokan',
 'jutter',
 'jutters',
 'kaput',
 'bunuh',
 'dibunuh',
 'pembunuh',
 'pembunuhan',
 'Killjoy',
 'membunuh',
 'bangsat',
 'pisau',
 'mengetuk',
 'diikat',
 'Kook',
 'kooky',
 'kekurangan',
 'sambil lewa',
 'kekurangan',
 'Bala',
 'lackeys',
 'kekurangan',
 'suram',
 'tidak mempunyai',
 'ringkas',
 'lag',
 'tertinggal',
 'ketinggalan',
 'laggy',
 'kecil sedemikian',
 'diberhentikan',
 'membidas',
 'mencercai',
 'lame',
 'lumpuh-bebek',
 'Ratapan',
 'patut disayangkan',
 'lamentably',
 'lesu',
 'merana',
 'kelesuan',
 'lembut hati',
 'languorously',
 'semampai',
 'berlalu',
 'luput',
 'kesilapan',
 'keberahian',
 'last-ditch',
 'kependaman',
 'menggelikan',
 'laughably',
 'tertawaan',
 'melanggar undang-undang',
 'lawbreaking',
 'tanpa undang-undang',
 'terkawal',
 'PHK',
 'PHK-happy',
 'malas',
 'kebocoran',
 'kebocoran',
 'ketirisan',
 'bocor',
 'kebocoran',
 'bocor',
 'lech',
 'bandot',
 'Didik',
 'pelepasan nafsu berahi',
 'lintah',
 'leer',
 'sangsi',
 'berhaluan kiri',
 'lemon',
 'panjang',
 'kurang maju',
 'yang kurang diketahui',
 'Letch',
 'maut',
 'lesu',
 'kelesuan',
 'lucah',
 'lewdly',
 'perbuatan yang keji',
 'liabiliti',
 'bertanggungjawab',
 'pembohong',
 'pembohong',
 'jangak',
 'licentiously',
 'percabulan',
 'dusta',
 'berbohong',
 'penipu',
 'pembohongan',
 'mengancam nyawa',
 'tidak bermaya',
 'had',
 'had',
 'batasan',
 'terhad',
 'had',
 'tempang',
 'tidak bermaya',
 'sedar undang-undang',
 'sedikit diketahui',
 'lebam',
 'lividly',
 'enggan',
 'benci',
 'kebencian',
 'loathly',
 'menjijikkan',
 'loathsomely',
 'lone',
 'kesepian',
 'kesepian',
 'penyendiri',
 'sepi',
 'lama',
 'panjang lebar',
 'rindu',
 'rindu',
 'kelemahan',
 'kelemahan',
 'longgar',
 'barang rampasan',
 'yg ditinggalkan',
 'kehilangan',
 'yang kalah',
 'rugi',
 'kehilangan',
 'kehilangan',
 'kehilangan',
 'kerugian',
 'hilang',
 'kuat',
 'kuat',
 'buruk',
 'tanpa cinta',
 'mabuk kepayang',
 'rendah diberi nilai',
 'hina',
 'lucu',
 'sangatlah',
 'penuh kesedihan',
 'suam',
 'meredakan',
 'lumpy',
 'orang gila',
 'lunaticism',
 'kesusahan',
 'umpan',
 'yg mendebarkan',
 'bersembunyi',
 'mengintai',
 'berbaring',
 'mengerikan',
 'gila',
 'madden',
 'menjengkelkan',
 'maddeningly',
 'madder',
 'bingung',
 'orang gila',
 'kegilaan',
 'tak dpt menyesuaikan diri',
 'Ketidakupayaan menyesuaikan diri',
 'malady',
 'kemalasan',
 'yg tdk puas',
 'malcontented',
 'maledict',
 'kebusukan hati',
 'jahat',
 'malevolently',
 'niat jahat',
 'berniat jahat',
 'niat jahat',
 'maliciousness',
 'memburuk-burukkan',
 'malignan',
 'berbau busuk',
 'penganiayaan',
 'mangle',
 'remuk',
 'Mangles',
 'pencacatan',
 'mania',
 'gila',
 'gila',
 'manik',
 'memanipulasi',
 'manipulasi',
 'manipulatif',
 'manipulator',
 'mar',
 'marginal',
 'sedikit',
 'syahid',
 'syahid-seeking',
 'lecek',
 'pembunuhan beramai-ramai',
 'pembunuhan beramai-ramai',
 'matte',
 'terlalu manis',
 'mawkishly',
 'mawkishness',
 'tidak seberapa',
 'bermakna',
 'kejahatan',
 'kecil sekali',
 'masuk campur',
 'meddlesome',
 'Keyakinan',
 'biasa-biasa saja',
 'melankolik',
 'pemain sandiwara',
 'melodramatically',
 'krisis',
 'ancaman',
 'mengancam',
 'menacingly',
 'yg suka berbohong',
 'dusta',
 'mengotorkan tangan',
 'tanpa belas kasihan',
 'tanpa belas kasihan',
 'keadaan huru-hara',
 'merosakkan',
 'messes',
 'main',
 'kemas',
 'leco',
 'MIFF',
 'militan',
 'tidak wajar',
 'tanpa berfikir',
 'fatamorgana',
 'mire',
 'misalign',
 'tidak sejajar',
 'misaligns',
 'salah paham',
 'bertindak tdk pantas',
 'misbecoming',
 'haram jadah',
 'tidak berfungsi dengan betul',
 'salah laku',
 'keliru perhitungan',
 'salah perhitungan',
 'pelbagai',
 'kerosakan',
 'nakal',
 'mischievously',
 'salah faham',
 'salah faham',
 'penjahat',
 'derhaka',
 'muslihat',
 'bakhil',
 'sengsara',
 'miserableness',
 'teruk',
 'kesengsaraan',
 'bakhil',
 'kesengsaraan',
 'tak padan',
 'nasib malang',
 'perasaan waswas',
 'ragu-ragu',
 'kesesatan',
 'menyesatkan',
 'sesat',
 'menyalahgunakan',
 'kejadian yang tidak diingini',
 'perundangan atau politik',
 'maklumat salah',
 'menyalahtafsirkan',
 'salah menilai',
 'salah fikiran',
 'mengelirukan',
 'mengelirukan',
 'mengelirukan',
 'mislike',
 'mismanage',
 'salah mengucapkan',
 'mispronounced',
 'mispronounces',
 'salah membaca',
 'salah baca',
 'memberi gambaran yang salah',
 'salah nyata',
 'miss',
 'terlepas',
 'tersasar',
 'salah nyata',
 'kabus',
 'kesilapan',
 'silap',
 'tersilap',
 'kesilapan',
 'mistified',
 'perempuan simpanan',
 'ketidakpercayaan',
 'yg tdk percaya',
 'mistrustfully',
 'kabus',
 'salah faham',
 'salah faham',
 'salah faham',
 'salah faham',
 'salah guna',
 'mengerang',
 'mobster',
 'olok-olok',
 'mengejek',
 'sindiran',
 'penghinaan',
 'mengejek',
 'mengejek',
 'ejek-ejekan',
 'menyakiti',
 'mencabul',
 'membosankan',
 'kebosanan',
 'raksasa',
 'monstrosities',
 'barang ganjil',
 'besar salahnya',
 'monstrously',
 'moody',
 'moot',
 'bermuram',
 'mengerikan',
 'tdk sihat',
 'pedas',
 'mordantly',
 'hampir menemui ajal',
 'dungu',
 'Pandir',
 'bodoh',
 'sakit hati',
 'mortified',
 'menyinggung perasaan',
 'memalukan',
 'bergerak-gerak',
 'bermacam-macam warna',
 'berkabung',
 'berkabung',
 'sedih',
 'redup',
 'Kekacauan',
 'berlumpur',
 'tukang fitnah',
 'pengumpatan',
 'seperti keldai',
 'pelbagai polarisasi',
 'biasa',
 'pembunuhan',
 'pembunuh',
 'membunuh',
 'murderously',
 'keruh',
 'otot-lenturan',
 'benyek',
 'hapak',
 'misteri',
 'misteri',
 'misteri',
 'membingungkan',
 'mitos',
 'mengomel',
 'membebel',
 'naif',
 'naif',
 'sempit',
 'buruk sekali',
 'nastiness',
 'jahat',
 'nakal',
 'menjijiki',
 'nauseates',
 'memualkan',
 'nauseatingly',
 'nave',
 'samar',
 'nebulously',
 'yang sia-sia',
 'sia-sia',
 'memerlukan',
 'jahat',
 'nefariously',
 'menafikan',
 'Penafian',
 'negatif',
 'negatif',
 'negatif',
 'pengabaian',
 'diabaikan',
 'kecuaian',
 'cuai',
 'musuh',
 'nepotisme',
 'saraf',
 'cemas',
 'gemuruh',
 'Jelatang',
 'nettlesome',
 'neurotik',
 'neurotically',
 'niggle',
 'niggles',
 'mimpi ngeri',
 'mimpi buruk',
 'nightmarishly',
 'nitpick',
 'nitpicking',
 'bunyi',
 'bunyi',
 'bising',
 'bising',
 'bukan keyakinan',
 'tidak wujud',
 'responsif',
 'karut',
 'yg ingin tahu',
 'terkenal',
 'terkenal',
 'terkenal',
 'berbahaya',
 'kacau ganggu',
 'kebas',
 'gemuk',
 'objek',
 'bantahan',
 'menyenangkan',
 'bantahan',
 'serong',
 'memusnahkan',
 'dipadamkan',
 'sedar',
 'menjijikkan',
 'obnoxiously',
 'lucah',
 'mesum',
 'kelucahan',
 'kabur',
 'dikaburi',
 'mengaburi',
 'kekaburan',
 'obses',
 'keterlaluan',
 'obsessively',
 'obsessiveness',
 'usang',
 'halangan',
 'keras kepala',
 'musyrik',
 'menghalang',
 'terhalang',
 'Menghalang',
 'halangan',
 'menghalang',
 'menonjol',
 'bodoh',
 'menutup jalan',
 'tersumbat',
 'occludes',
 'menyekat aliran darah',
 'ganjil',
 'Odder',
 'oddest',
 'menimbulkan kejanggalan',
 'keanehan',
 'aneh',
 'bau',
 'kesalahan',
 'menyinggung perasaan',
 'pesalah',
 'bersalah',
 'kesalahan',
 'menyakitkan',
 'sopan',
 'offensiveness',
 'tdk rasmi',
 'menyenangkan',
 'membimbangkan',
 'peninggalan',
 'meninggalkan',
 'berat sebelah',
 'membebankan',
 'dgn sukar',
 'serangan',
 'keras kepala',
 'lawan',
 'oportunis',
 'menentang',
 'pembangkang',
 'pembangkang',
 'menindas',
 'penindasan',
 'menindas',
 'menindas',
 'penindasan',
 'penindas',
 'pengalaman pahit',
 'anak yatim',
 'memulaukan',
 'wabak',
 'cetusan',
 'ledakan',
 'orang buangan',
 'bantahan',
 'mengharamkan',
 'ketinggalan zaman',
 'kemarahan',
 'marah',
 'keterlaluan',
 'terlampau',
 'outrageousness',
 'outrages',
 'orang luar',
 'lebih-bertindak',
 'lebih-kagum',
 'lebih seimbang',
 'lebih-hyped',
 'terlampau mahal',
 'lebih-penilaian',
 'bermain melampaui batas',
 'overacted',
 'menimbulkan rasa kagum',
 'imbangan',
 'overbalanced',
 'sombong',
 'overbearingly',
 'yg berkembang sama sekali',
 'keterlaluan',
 'dilebih-lebihkan',
 'tertunggak',
 'terlebih menekankan',
 'terlalu panas',
 'pembunuhan besar-besaran',
 'beban',
 'menghadap',
 'terlebih bayar',
 'overpayed',
 'bermain melampaui batas',
 'menguasai',
 'terlalu mahal',
 'berubah mengikut',
 'tarbiah',
 'ditakluki',
 'menaungi',
 'pengawasan',
 'disengajakan',
 'melampaui batas',
 'terlalu dipermudahkan',
 'menggampangkan',
 'terlalu besar',
 'terlalu keras menekankan',
 'remeh',
 'terlebih nyata',
 'terlebihnyata',
 'hubs',
 'overtaxed',
 'penggulingan',
 'menggulingkan',
 'mengubah',
 'berat badan berlebihan',
 'mengatasi',
 'terharu',
 'hangat',
 'overwhelmingly',
 'dikelilingi',
 'keterlaluan',
 'berlebih-lebihan',
 'overzelous',
 'kesakitan',
 'menyakitkan',
 'painfull',
 'menyakitkan',
 'sakit',
 'pucat',
 'jauh lebih rendah',
 'remeh',
 'pan',
 'huru-hara',
 'calo',
 'memuaskan nafsu',
 'panders',
 'panik',
 'panick',
 'panik',
 'panik',
 'panik',
 'paradoks',
 'paradoks',
 'paralize',
 'lumpuh',
 'paranoia',
 'paranoid',
 'parasit',
 'pariah',
 'parodi',
 'berat sebelah',
 'partisan',
 'partisan',
 'passe',
 'pasif',
 'ketidakpedulian',
 'kasihan',
 'menyedihkan',
 'mengunjungi',
 'kekurangan',
 'papa',
 'paupers',
 'bayaran balik',
 'pelik',
 'khususnya',
 'bengah',
 'dikupas',
 'mengesalkan',
 'kesal',
 'jengkel',
 'peevishly',
 'menghukum',
 'penalti',
 'durhaka',
 'perfidity',
 'acuh tak acuh',
 'bahaya dengan',
 'berbahaya',
 'perilously',
 'binasa',
 'merosakkan',
 'mengacau',
 'bingung',
 'membingungkan',
 'kebingungan',
 'menganiaya',
 'penganiayaan',
 'keras kepala',
 'pertinaciously',
 'ketabahan',
 'menggangu',
 'risau',
 'berleluasa',
 'yang sesat,',
 'perversely',
 'penyelewengan',
 'kesesatan',
 'pervert',
 'sesat',
 'orang-orang sesat',
 'pesimisme',
 'pesimis',
 'pessimistically',
 'perosak',
 'berbisa',
 'petrified',
 'membatu',
 'bertengkar tiada alasan yg',
 'kecil',
 'fobia',
 'phobic',
 'palsu',
 'piket',
 'berpiket',
 'berpiket',
 'piket',
 'cerewet',
 'babi',
 'babi',
 'penjarahan',
 'mengumumkan kesalahan',
 'jerawat',
 'picit',
 'pique',
 'yg menyedihkan',
 'menyedihkan',
 'pitifully',
 'kekejaman',
 'pitilessly',
 'jumlah sedikit',
 'kasihan',
 'meniru tulisan',
 'tulah',
 'plasticky',
 'mainan',
 'pengakuan',
 'rayuan',
 'kampungan',
 'nasib',
 'plot',
 'tipu daya',
 'helah',
 'rampasan',
 'perompak',
 'sia-sia',
 'pointlessly',
 'racun',
 'beracun',
 'poisonously',
 'muslihat',
 'poky',
 'polarisasi',
 'mempolemikkan',
 'mencemarkan',
 'pencemar',
 'pencemaran',
 'pencemaran',
 'sombong',
 'miskin',
 'miskin',
 'termiskin',
 'kurang',
 'pendirian',
 'merengus',
 'kemiskinan',
 'tidak berkuasa',
 'omong kosong',
 'pratfall',
 'ocehan',
 'tidak menentu',
 'dalam keadaan berbahaya',
 'mendakan',
 'terjal',
 'pemangsa',
 'kesusahan',
 'menghukum',
 'menjejaskan',
 'prasangka',
 'memudaratkan',
 'yg direncanakan terlebih dahulu',
 'mengasyikkan',
 'tidak munasabah',
 'preposterously',
 'angkuh',
 'angkuh',
 'berpura-pura',
 'berpura-pura',
 'berpura-pura',
 'Anggun',
 'pretentiously',
 'berbohong',
 'mahal',
 'pricier',
 'cucuk',
 'duri',
 'prickles',
 'sombong',
 'Prik',
 'primitif',
 'penjara',
 'banduan',
 'masalah',
 'bermasalah',
 'masalah',
 'berlengah-lengah',
 'procrastinates',
 'procrastination',
 'duniawi',
 'kata-kata kotor',
 'melarang',
 'terlalu tinggi',
 'terlampau',
 'propaganda',
 'mempropagandakan',
 'proprietari',
 'mendakwa',
 'protes',
 'membantah',
 'membantah',
 'protes',
 'berlarutan',
 'provokasi',
 'provokatif',
 'mencetuskan',
 'pry',
 'garang',
 'pugnaciously',
 'kegarangan',
 'punch',
 'menghukum',
 'boleh dihukum',
 'punitif',
 'punk',
 'puny',
 'boneka',
 'boneka',
 'hairan',
 'kebingungan',
 'membingungkan',
 'dukun',
 'rasa cemas',
 'ragu-ragu',
 'keadaan serba salah',
 'pergaduhan',
 'quarrellous',
 'quarrellously',
 'pertengkaran',
 'suka bertengkar',
 'membatalkan',
 'aneh',
 'dipersoalkan',
 'berdalih',
 'quibbles',
 'yg berhenti berusaha',
 'fanatik',
 'perkauman',
 'perkauman',
 'rasis',
 'agak lucah',
 'radikal',
 'radikal',
 'radikal',
 'radikal',
 'kemarahan',
 'bergerigis',
 'mengamuk',
 'kereta api',
 'meraih',
 'mengamuk',
 'berleluasa',
 'hampir roboh',
 'dendam kesumat',
 'secara rawak',
 'tertanam di hati',
 'kata-kata kasar',
 'ranted',
 'Ranting',
 'rantingly',
 'rants',
 'rogol',
 'dirogol',
 'merogol',
 'rascal',
 'penyangak',
 'ruam',
 'rattle',
 'bingung',
 'mainan kerincingan',
 'membinasakan',
 'meracau',
 'reaksioner',
 'derhaka',
 'menolak',
 'teguran',
 'keras kepala',
 'menarik balik',
 'kemelesetan',
 'kemelesetan',
 'melulu',
 'melulu',
 'perbuatan melulu',
 'berundur',
 'recourses',
 'lebihan',
 'berlebihan',
 'keengganan',
 'menolak',
 'enggan',
 'enggan',
 'Enggan',
 'penyangkalan',
 'menyangkal',
 'menafikan',
 'Nafi',
 'menyangkal',
 'mundur',
 'regresi',
 'regresif',
 'menyesal',
 'regreted',
 'penyesalan',
 'kesal',
 'penyesalan',
 'dikesali',
 'malangnya',
 'kesal',
 'menolak',
 'ditolak',
 'menolak',
 'penolakan',
 'menolak',
 'berulang',
 'tidak henti-henti',
 'lumus',
 'relentlessness',
 'keengganan',
 'enggan',
 'berat hati',
 'penyesalan',
 'menyesal',
 'remorsefully',
 'kejam',
 'seberat-beratnya',
 'remorselessness',
 'keluar daripada agama',
 'penolakan',
 'menghalau',
 'berulang-ulang',
 'tercela',
 'reprehensibly',
 'umpat',
 'reprehensive',
 'menindas',
 'penindasan',
 'menindas',
 'teguran',
 'teguran',
 'comelan',
 'menegur',
 'reprovingly',
 'menjauh',
 'penolakan',
 'memualkan',
 'kebencian',
 'menjijikkan',
 'repugnantly',
 'menangkis',
 'ditangkis',
 'repulsing',
 'menjijikkan',
 'repulsively',
 'repulsiveness',
 'membenci',
 'geram',
 'kebencian',
 'peletakan jawatan',
 'meletak jawatan',
 'rintangan',
 'resah',
 'kegelisahan',
 'menyekat',
 'terhad',
 'sekatan',
 'ketat',
 'kebangkitan',
 'bertindak balas',
 'balas',
 'retard',
 'akal',
 'retardedness',
 'melambatkan',
 'diam-diam',
 'menarik balik',
 'berundur',
 'berundur',
 'membalas dendam',
 'berdendam',
 'revengefully',
 'kembali',
 'mencaci',
 'dicerca',
 'membatalkan',
 'pemberontakan',
 'memberontak',
 'revoltingly',
 'jijik',
 'yg membelok perhatian',
 'rhapsodize',
 'retorik',
 'retorik',
 'ricer',
 'ejekan',
 'mencemuh',
 'tidak masuk akal',
 'sungguh',
 'bertiup kencang',
 'perselisihan',
 'Perselisihan',
 'tegar',
 'ketegaran',
 'rigidness',
 'menggusarkan',
 'mencetuskan kemarahan',
 'rip',
 'rip-off',
 'ripoff',
 'ripped',
 'risiko',
 'risiko',
 'berisiko',
 'saingan',
 'persaingan',
 'sekatan jalan raya',
 'berbatu',
 'penyangak',
 'rollercoaster',
 'reput',
 'busuk',
 'kasar',
 'rremediable',
 'sampah',
 'kurang ajar',
 'rue',
 'bengis',
 'ruffle',
 'kehancuran',
 'hancur',
 'merosakkan',
 'puing',
 'runtuhan',
 'gegaran',
 'khabar angin',
 'khabar angin',
 'khabar angin',
 'mengumalkan',
 'daif',
 'melarikan diri',
 'pecah',
 'karat',
 'berkarat',
 'berkarat',
 'rut',
 'kejam',
 'kejam',
 'kekejaman',
 'aluran',
 'sabotaj',
 'karung',
 'dikorbankan',
 'sedih',
 'memuramkan',
 'sedih',
 'kesedihan',
 'sag',
 'sagged',
 'kendur',
 'kendor',
 'sags',
 'gasang',
 'sanctimonious',
 'sap',
 'sindiran',
 'menyindir',
 'sinis',
 'tajam',
 'dgn sengit',
 'sass',
 'menyindir',
 'menyindir',
 'ganas',
 'savaged',
 'kekejaman',
 'liar',
 'bersisik',
 'penipuan',
 'penipuan',
 'skandal',
 'memalukan',
 'memalukan',
 'skandal',
 'scandalously',
 'skandal',
 'scandel',
 'scandels',
 'daya terhad',
 'kambing hitam',
 'parut',
 'terhad',
 'hampir-hampir tidak',
 'kekurangan',
 'menakutkan',
 'takut',
 'menakutkan',
 'paling menakutkan',
 'menakutkan karena',
 'berparut',
 'parut',
 'menakutkan',
 'pedas',
 'scathingly',
 'ragu-ragu',
 'mencemuh',
 'mengejek',
 'memarahi',
 'dimarahi',
 'memarahi',
 'scoldingly',
 'terik',
 'scorchingly',
 'cemuhan',
 'sombong takbur',
 'benci',
 'bangsat',
 'musuh nombor',
 'pandangan marah',
 'perebutan',
 'hancur',
 'scrambles',
 'berebut',
 'sekerap',
 'calar',
 'tercalar',
 'calar',
 'menggarut',
 'menjerit',
 'berciut',
 'skru-up',
 'diskrukan',
 'diskrukan-up',
 'screwy',
 'scuff',
 'scuffs',
 'buih',
 'berbuih',
 'kelas kedua',
 'tahap kedua',
 'berahsia',
 'sedentari',
 'keadaan buruk',
 'didihan',
 'meluap-luap',
 'rampasan kuasa diri',
 'mengkritik diri sendiri',
 'merugikan diri sendiri',
 'merosakkan diri',
 'penghinaan diri',
 'kepentingan diri',
 'sendiri berminat',
 'layan diri',
 'selfinterested',
 'mementingkan diri sendiri',
 'kepentingan sendiri',
 'mementingkan diri',
 'separuh akal',
 'nyanyuk',
 'mensensasikan',
 'tidak masuk akal',
 'senselessly',
 'kesungguhan',
 'berkhotbah',
 'perhambaan',
 'set-up',
 'kemunduran',
 'halangan',
 'memutuskan',
 'teruk',
 'keterukan',
 'sh * t',
 'lusuh',
 'bayangan',
 'rendang',
 'goncang',
 'goyah',
 'cetek',
 'sham',
 'pertumpahan darah',
 'malu',
 'memalukan',
 'memalukan',
 'shamefulness',
 'tahu malu',
 'malu',
 'shamelessness',
 'yu',
 'mendadak',
 'menghancurkan',
 'shemale',
 'berkilau',
 'shimmy',
 'kapal karam',
 'syirik',
 'pengelak',
 'najis',
 'menggigil',
 'terkejut',
 'terkejut',
 'mengejutkan',
 'teramat',
 'kurang bermutu',
 'kekal lama',
 'kekurangan',
 'shortchange',
 'kelemahan',
 'kelemahan',
 'sesak',
 'rabun jauh',
 'rabun jauh',
 'pertarungan',
 'shrew',
 'tertawa terpingkal',
 'nyaring',
 'nyaring',
 'menjadi layu',
 'kain kafan',
 'diselubungi',
 'mengangkat bahu',
 'shun',
 'dijauhi',
 'sakit',
 'jatuh sakit',
 'menjijikkan',
 'menjijikkan',
 'uzur',
 'penyakit',
 'jalan menyimpang',
 'terjerumus',
 'pengepungan',
 'sillily',
 'bodoh',
 'simplistik',
 'simplistically',
 'dosa',
 'berdosa',
 'dusta',
 'jahat',
 'sinisterly',
 'sink',
 'tenggelam',
 'rangka',
 'curiga',
 'ragu-ragu',
 'skeptically',
 'keraguan',
 'tidak lengkap',
 'sangat sempit',
 'kurus',
 'keras kepala',
 'skittishly',
 'menghindari pekerjaan',
 'kendur',
 'fitnah',
 'pemfitnah',
 'fitnah',
 'slanderously',
 'fitnah',
 'tamparan',
 'pemotongan',
 'penyembelihan',
 'disembelih',
 'hamba',
 'hamba',
 'kotor',
 'lendir',
 'bekerja keras',
 'mampat',
 'melanda',
 'slogs',
 'sloooooooooooooow',
 'sloooow',
 'slooow',
 'sloow',
 'sloppily',
 'ceroboh',
 'kemalasan',
 'malas',
 'perlahan',
 'bergerak perlahan',
 'perlahan',
 'lebih perlahan',
 'paling perlahan',
 'perlahan-lahan',
 'sloww',
 'slowww',
 'slowwww',
 'slug',
 'lembap',
 'kemerosotan',
 'kejatuhan',
 'slumpping',
 'penghinaan',
 'perempuan murahan',
 'sluts',
 'diam-diam',
 'perahu nelayan kecil',
 'smallish',
 'smash',
 'smear',
 'bau',
 'berbau',
 'berbau',
 'bau',
 'berbau',
 'dihidu',
 'asap',
 'tabir',
 'membara',
 'membara',
 'memadamkan',
 'membara',
 'membara',
 'noda',
 'dikotori',
 'smudges',
 'mencoreng',
 'sombong',
 'smugly',
 'smut',
 'smuttier',
 'smuttiest',
 'kotor',
 'tergendala',
 'tersangkut',
 'Tersangkut',
 'snags',
 'yg suka menggigit',
 'snappishly',
 'jerat',
 'snarky',
 'mata kayu',
 'menyelinap',
 'sneakily',
 'sneaky',
 'menyeringai',
 'yg mengejek',
 'mengejek',
 'yg suka',
 'gila hormat',
 'tinggi hati',
 'snobish',
 'snobs',
 'menghina',
 'apa cal',
 'sabun',
 'sob',
 'sedar diri',
 'yg menenangkan',
 'dengan penuh',
 'solicitude',
 'muram',
 'sakit',
 'amat',
 'kesakitan',
 'kesedihan',
 'sedih',
 'sedih',
 'maaf',
 'masam',
 'sourly',
 'spade',
 'merotan',
 'Spendy',
 'memuntahkan',
 'dimuntahkan',
 'memuntahkan',
 'SPEWS',
 'tertumpah',
 'anak dara tua',
 'bacul',
 'walaupun',
 'dengki',
 'spitefully',
 'spitefulness',
 'berhamburan',
 'split',
 'membelah',
 'merosakkan',
 'kerosakan',
 'spoilages',
 'manja',
 'spoilled',
 'harta rampasan',
 'hantu',
 'spookier',
 'spookiest',
 'spookily',
 'seram',
 'sudu-makan',
 'sogokan',
 'spoonfed',
 'sekali-sekala',
 'turun naik',
 'palsu',
 'memandang rendah',
 'terbatuk-batuk',
 'pertengkaran',
 'pertengkaran',
 'pemborosan',
 'skuasy',
 'mencicit',
 'squeaks',
 'nyaring',
 'pekik',
 'cengking',
 'squeals',
 'menggeliat-tiang',
 'tikaman',
 'bertakung',
 'bertakung',
 'genangan',
 'tenang dan serius',
 'noda',
 'kesan',
 'basi',
 'jalan buntu',
 'gerai',
 'gerai',
 'gagap',
 'rempuhan',
 'berdiri tegak',
 'sama sekali',
 'starkly',
 'menyentakkan',
 'mengejutkan',
 'startlingly',
 'kebuluran',
 'kebuluran',
 'statik',
 'mencuri',
 'mencuri',
 'mencuri',
 'curam',
 'curam',
 'bau busuk',
 'stereotaip',
 'stereotaip',
 'stereotaip',
 'tegas',
 'rebus',
 'melekit',
 'sengit',
 'kekakuan',
 'menyekat',
 'menyesakkan',
 'yang mencekik',
 'stigma',
 'mencela',
 'sengat',
 'rasa pedih',
 'stingingly',
 'kedekut',
 'berbau busuk',
 'berbau',
 'sukar dicerna',
 'mencuri',
 'dicuri',
 'kaki tangan',
 'tali barut',
 'ribut',
 'berjurai',
 'orang yg tersesat',
 'terikan',
 'tegang',
 'meneran',
 'pelik',
 'pelik',
 'orang asing',
 'pelik',
 'mencekik',
 'bercoret',
 'berat',
 'tekanan',
 'tekanan',
 'tertekan',
 'stressfully',
 'dilanda',
 'ketat',
 'tegas',
 'lantang',
 'lantang',
 'persengketaan',
 'mogok',
 'ketat',
 'ketat',
 'melanda',
 'perjuangan',
 'bergelut',
 'perjuangan',
 'berjuang',
 'topang',
 'degil',
 'berdegil',
 'kedegilan',
 'tersangkut',
 'tersumbat',
 'tersandung',
 'tersandung',
 'tersandung',
 'tunggul',
 'stumped',
 'tunggul',
 'menyebabkan pengsan',
 'aksi',
 'terbantut',
 'bodoh',
 'bodoh',
 'kebodohan',
 'bodoh',
 'stupified',
 'stupify',
 'pengsan',
 'gagap',
 'stuttered',
 'kegagapan',
 'gagap',
 'sty',
 'tersentap',
 'sub-par',
 'lemah',
 'tertakluk',
 'tunduk',
 'menundukkan',
 'penaklukan',
 'tunduk patuh',
 'bawahan',
 'sepina',
 'sepina',
 'sikap tunduk',
 'tunduk',
 'substandard',
 'tolak',
 'subversif',
 'subversif',
 'subversively',
 'menggulingkan',
 'tunduk',
 'menghisap',
 'disedut',
 'penyedut',
 'menghisap',
 'teruk,',
 'sue',
 'menyaman',
 'sueing',
 'Sues',
 'menderita',
 'mengalami',
 'pesakit',
 'pesakit',
 'mengalami',
 'menderita',
 'mati sesak nafas',
 'gula-coat',
 'bersalut gula',
 'bersalut gula',
 'membunuh diri',
 'bunuh diri',
 'merajuk',
 'merengus',
 'sully',
 'Sunder',
 'tenggelam',
 'tenggelam',
 'cetek',
 'kedangkalan',
 'sekali pandang',
 'diperlukan',
 'kepercayaan karut',
 'khurafat',
 'menindas',
 'penindasan',
 'penyerahan',
 'terdedah',
 'suspek',
 'syak wasangka',
 'syak wasangka',
 'mencurigakan',
 'mencurigakan',
 'kesombongan',
 'dibanjiri',
 'berpeluh',
 'bengkak',
 'bengkak',
 'penipuan',
 'sapu',
 'bengkak',
 'gejala',
 'gejala',
 'sindrom',
 'pantang',
 'lekat',
 'merosakkan',
 'tercemar',
 'mengusik',
 'kusut',
 'kusut',
 'kusut',
 'tangki',
 'mabuk',
 'tangki',
 'tantrum',
 'terlambat',
 'mencemarkan',
 'mencemarkan',
 'mencemarkan',
 'mencemarkan',
 'koyak',
 'ejekan',
 'mengejek',
 'mengejek',
 'ejekan',
 'tegang',
 'menonjol',
 'cukai',
 'menggoda',
 'teasingly',
 'membosankan',
 'tediously',
 'keberanian',
 'sabar',
 'badai',
 'godaan',
 'kelembutan',
 'tegang',
 'ketegangan',
 'tentatif',
 'tentatif',
 'renggang',
 'memegang dengan',
 'suam-suam kuku',
 'dahsyat',
 'terribleness',
 'betul-betul',
 'keganasan',
 'keganasan genic',
 'keganasan',
 'mengganas',
 'bengkeng',
 'mudah tersinggung',
 'tetchily',
 'mudah tersinggung',
 'lagi amat tidak bersyukur',
 'tebal',
 'dahaga',
 'berduri',
 'berfikir dahulu',
 'thoughtlessly',
 'kealpaan',
 'sampah',
 'ancaman',
 'mengancam',
 'mengancam',
 'ancaman',
 'bertiga',
 'berdenyut',
 'throbbed',
 'berdenyut',
 'throbs',
 'pendikit',
 'samseng',
 'ibu jari ke bawah',
 'tak bagus',
 'menggagalkan',
 'mengambil masa',
 'malu-malu',
 'sifat malu-malu',
 'dgn malu-malu',
 'timidness',
 'tin-y',
 'tingled',
 'kesemutan',
 'letih',
 'meletihkan',
 'memenatkan',
 'tiringly',
 'kesusahan',
 'tol',
 'top-berat',
 'menggulingkan',
 'azab',
 'diseksa',
 'torrent',
 'rumit',
 'penyeksaan',
 'diseksa',
 'penderaan',
 'mendera',
 'menyeksa',
 'torturously',
 'totalitarian',
 'sensitif',
 'kekuatan',
 'tout',
 'disebut-sebut',
 'ulat',
 'toksik',
 'mengumpat',
 'tragedi',
 'tragik',
 'tragedi',
 'pengkhianat',
 'pengkhianat',
 'khianat',
 'tramp',
 'memijak',
 'melampaui batas',
 'pelanggaran',
 'perangkap',
 'traped',
 'terperangkap',
 'sampah',
 'dibuang',
 'rongsok',
 'trauma',
 'trauma',
 'traumatically',
 'traumatize',
 'trauma',
 'travesties',
 'persendaan',
 'khianat',
 'setia',
 'pengkhianatan',
 'pengkhianatan',
 'khianat',
 'silap mata',
 'ditipu',
 'tipu muslihat',
 'rumit',
 'remeh',
 'remeh',
 'masalah',
 'bermasalah',
 'pembuat masalah',
 'masalah',
 'menyusahkan',
 'troublesomely',
 'merisaukan',
 'troublingly',
 'ponteng',
 'jatuh',
 'jatuh',
 'tumbles',
 'huru-hara',
 'bergelora',
 'kegawatan',
 'twist',
 'twisted',
 'kelainan',
 'Talam dua muka',
 'dua muka',
 'zalim',
 'penindasan',
 'kezaliman',
 'kejam',
 'ugh',
 'uglier',
 'seburuk',
 'kehodohan',
 'hodoh',
 'tersembunyi',
 'kata dua',
 'kata dua',
 'ultra-garis keras',
 'un-mana boleh dilihat',
 'dapat',
 'tidak boleh diterima',
 'unacceptablely',
 'tidak boleh diterima',
 'unaccessible',
 'tak biasa',
 'mungkin sukar untuk dicapai',
 'mahal',
 'tidak menarik',
 'tidak menarik',
 'tidak sahih',
 'tidak tersedia',
 'tidak dapat dielakkan',
 'tidak tertanggung',
 'unbearablely',
 'sukar dipercayai',
 'unbelievably',
 'peduli',
 'yang tidak menentu',
 'uncivil',
 'tidak bertamadun',
 'bersih',
 'tidak jelas',
 'tidak dapat dikutip',
 'tidak selesa',
 'tidak selesa',
 'uncomfy',
 'tidak kompetitif',
 'tanpa kompromi',
 'tegas',
 'yang belum disahkan',
 'perlembagaan',
 'tidak terkawal',
 'tidak meyakinkan',
 'unconvincingly',
 'memberikan kerjasama',
 'senonoh',
 'tidak kreatif',
 'belum membuat keputusan',
 'undefined',
 'undependability',
 'undependable',
 'melemahkan',
 'makan bawah',
 'pemotongan',
 'underdog',
 'memandang rendah',
 'bawahannya',
 'melemahkan',
 'terjejas',
 'melemahkan',
 'melemahkan',
 'underpaid',
 'underpowered',
 'berukuran',
 'yang tidak diingini',
 'tidak dapat ditentukan',
 'undid',
 'tdk pantas',
 'larut',
 'tanpa izin',
 'belum dilakukan',
 'yang tidak wajar',
 'tidak senang',
 'gelisah',
 'keresahan',
 'tidak selesa',
 'tidak ekonomi',
 'menganggur',
 'yang tidak sama rata',
 'tidak beretika',
 'tidak sekata',
 'peristiwanya',
 'yang tidak dijangka',
 'tidak disangka-sangka',
 'yang tidak dapat dijelaskan',
 'tidak adil',
 'setia',
 'setia',
 'yang tidak dikenali',
 'tidak menguntungkan',
 'berperasaan',
 'belum selesai',
 'tidak layak',
 'yang tidak diduga',
 'tidak bertimbang rasa',
 'malang',
 'malangnya',
 'tidak berasas',
 'tidak mesra',
 'tidak dipenuhi',
 'tidak dibiayai',
 'tak terkendalikan',
 'tidak bersyukur',
 'malangnya',
 'rasa tidak puas hati',
 'tidak berpuas hati',
 'tidak sihat',
 'tidak suka membantu',
 'unilateralisme',
 'tidak dapat dibayangkan',
 'unimaginably',
 'tidak penting',
 'kurang arif',
 'tidak diinsuranskan',
 'difahami',
 'unintelligile',
 'unipolar',
 'adil',
 'tidak wajar',
 'unjustifiably',
 'tidak wajar',
 'zalim',
 'tidak baik',
 'unkindly',
 'tidak diketahui',
 'unlamentable',
 'unlamentably',
 'menyalahi undang-undang',
 'menyalahi undang-undang',
 'keharaman',
 'melepaskan',
 'tidak berlesen',
 'tidak mungkin',
 'malang',
 'yg tak berubah',
 'luar biasa',
 'unnaturally',
 'yang tidak perlu',
 'yang tidak diperlukan',
 'mengerikan',
 'terkesima',
 'melemahkan semangat',
 'unnervingly',
 'tanpa disedari',
 'unobserved',
 'ortodoks',
 'ortodoks',
 'tidak menyenangkan',
 'unpleasantries',
 'tidak popular',
 'tidak menentu',
 'bersedia',
 'tidak produktif',
 'tidak menguntungkan',
 'unprove',
 'tdk terbukti',
 'terbukti',
 'unproves',
 'unproving',
 'yang tidak berkelayakan',
 'membongkar',
 'dibongkar',
 'tidak dapat dihubungi',
 'tidak boleh dibaca',
 'tidak realistik',
 'tidak munasabah',
 'tidak munasabah',
 'tak henti-henti',
 'unrelentingly',
 'unreliability',
 'tidak boleh dipercayai',
 'tidak dapat diselesaikan',
 'tidak responsif',
 'pergolakan',
 'sukar dikawal',
 'tidak selamat',
 'tidak memuaskan',
 'buruk',
 'yang tidak bertanggungjawab',
 'unscrupulously',
 'tak terjamin',
 'tak layak',
 'menggoncang',
 'tidak selesai',
 'menyenangkan',
 'unsettlingly',
 'tidak mahir',
 'canggih',
 'tidak kukuh',
 'tidak terkata',
 'unspeakablely',
 'tidak ditentukan',
 'tidak stabil',
 'unsteadily',
 'kegoyangan',
 'tidak stabil',
 'tidak berjaya',
 'tidak berjaya',
 'tidak disokong',
 'unsupportive',
 'pasti',
 'tidak curiga',
 'tidak mapan',
 'tidak dapat dipertahankan',
 'belum dicuba',
 'difikirkan',
 'unthinkably',
 'terlalu cepat',
 'tidak disentuh',
 'tidak benar',
 'tidak boleh dipercayai',
 'tidak benar',
 'tidak boleh digunakan',
 'unusably',
 'unuseable',
 'unuseably',
 'luar biasa',
 'luar biasa',
 'tidak boleh dilihat',
 'yang tidak diingini',
 'tidak munasabah',
 'unwatchable',
 'tidak diundang',
 'tidak sihat',
 'dikawal',
 'enggan',
 'terpaksa',
 'tidak rela',
 'kurang bijak',
 'tidak bijaksana',
 'tidak boleh dilaksanakan',
 'tidak layak',
 'pantang menyerah',
 'mencelakan',
 'pergolakan',
 'pemberontakan',
 'kegemparan',
 'hingar-bingar',
 'berdekah-dekah',
 'uproarous',
 'uproarously',
 'mencabut',
 'kecewa',
 'upseting',
 'gangguan',
 'menyakitkan',
 'upsettingly',
 'segera',
 'tidak berguna',
 'merebut',
 'perampas kuasa',
 'sama sekali',
 'yg berkeliaran',
 'samar-samar',
 'kekaburan',
 'sia-sia',
 'dgn sia-sia',
 'sia-sia',
 'keras',
 'sekeras-kerasnya',
 'dendam',
 'pendendam',
 'vengefully',
 'berdendam',
 'racun',
 'berbisa',
 'venomously',
 'melepaskan',
 'sisa-sisa',
 'menyakiti',
 'Kekesalan',
 'yg menyusahkan',
 'vexingly',
 'bergetar',
 'digetarkan',
 'bergetar',
 'bergetar',
 'getaran',
 'Naib',
 'ganas',
 'kejam',
 'kejahatan',
 'mengorbankan',
 'keji',
 'kekejian',
 'memburuk-burukkan',
 'keji',
 'villainously',
 'penjahat',
 'villian',
 'villianous',
 'villianously',
 'villify',
 'pendendam',
 'vindictively',
 'dendam',
 'melanggar',
 'pelanggaran',
 'pelanggar',
 'pesalah',
 'ganas',
 'ganas',
 'viper',
 'kebisaan',
 'getir',
 'virulently',
 'virus',
 'riuh rendah',
 'lantang',
 'tidak menentu',
 'turun naik',
 'muntah',
 'muntah',
 'muntah',
 'muntah',
 'kesat',
 'terdedah',
 'pukul',
 'meratap',
 'berkubang',
 'wane',
 'amaran',
 'melampaui batas',
 'perang seperti',
 'dgn berhati-hati',
 'sifat hati-hati',
 'suka berperang',
 'diberi amaran',
 'amaran',
 'meledingkan',
 'meleding',
 'berhati-hati',
 'dibasuh keluar',
 'membazir',
 'sia-sia',
 'membazir',
 'pembaziran',
 'membuang',
 'air-down',
 'disiram-down',
 'sesat',
 'lemah',
 'melemahkan',
 'kelemahan',
 'lemah',
 'kelemahan',
 'kelemahan',
 'keletihan',
 'meletihkan',
 'letih',
 'baji',
 'rumpai',
 'menangis',
 'pelik',
 'weirdly',
 'memujuk',
 'rengekan',
 'merengek',
 'merengek',
 'whiny',
 'cambuk',
 'pelacur',
 'whores',
 'jahat',
 'kejahatan',
 'kejahatan',
 'liar',
 'liar',
 'tipu muslihat',
 'layu',
 'cerdik',
 'Wimpy',
 'bergoyang-goyang',
 'wobbled',
 'wobbles',
 'celakalah',
 'woebegone',
 'seburuk-buruk',
 'sedih',
 'kaki perempuan',
 'kaki perempuan',
 'dipakai',
 'bimbang',
 'worriedly',
 'worrier',
 'kebimbangan',
 'membimbangkan',
 'bimbang',
 'membimbangkan',
 'membimbangkan',
 'lebih teruk',
 'memburukkan',
 'semakin teruk',
 'yang paling teruk',
 'tidak bernilai',
 'worthlessly',
 'tidak berguna',
 'luka',
 'luka',
 'percekcokan',
 'murka',
 'melampiaskan',
 'mendatangkan',
 'Riba mengakibatkan mala',
 'bangkai kapal',
 'merampas',
 'bertumbuk',
 'orang celaka',
 'celaka',
 'wretchedly',
 'keadaan yg',
 'kedut',
 'berkedut',
 'kedutan',
 'wrip',
 'wripped',
 'wripping',
 'sakit hati',
 'salah',
 'salah',
 'salah',
 'tempa',
 'menguap',
 'zap',
 'dibedil',
 'zaps',
 'fanatik',
 'bersemangat',
 'bersemangat',
 'zombie']

